### ISSUE TITLE
See if the computers in the staging room are useful replacements for the ones in the workshop

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#657] opened 2018-02-12 13:39 UTC
There are a load of Dell PCs left in the ex-call centre on the fifth floor (see #631 for more details on that), although it's not clear what state any of them are in.

They're mostly Dell Core Duo 2 machines, which feel like they'd be decent upgrades for some (all?) of the PCs in the workshop.

It's not clear what state they're in - at least some are marked as broken, and one that @goatchurchprime tried plugging in complained about a disk error - but it feels like it should be possible to get at least three or four working machines from the collection (and make sure all the RAM slots are populated, etc. to make the most of it).

We'd need someone to sort through them to find (enough) working ones, which we can then move down to reinstall with the standard "workshop PC build" that @ajlennon set up.

**Comment by ajlennon** [comment] 2018-02-12 15:04
I could have a look

**Comment by johnmckerrell** [comment] 2018-02-12 15:15
FYI they are en route to the staging room. I’ve confirmed that most have hard drives, 80GB for the ones I’ve checked.

**Comment by amcewen** [comment] 2018-02-12 18:27
They are now all in the staging room, in the "leave here" and "to be sold" area. Have at them whenever you like @ajlennon :-D

**Comment by SayBeano** [comment] 2018-02-12 19:43
Hey @ajlennon, I missed whatever PC "workshop build set up" notes there are, is this an install guide or an image?

**Comment by ajlennon** [comment] 2018-02-13 06:57
Hey @SayBeano, I left some notes from when I went through this loop last time

https://github.com/DoESLiverpool/wiki/wiki/PC-Systems

The installer files have been moved somewhere as they were eating up space. 

Does anybody have the new link?

**Comment by ajlennon** [comment] 2018-02-13 07:07
> Have at them whenever you like @ajlennon :-D

Fortune is guiding our affairs better than we ourselves could have wished. Do you see over yonder, friend Adrian, thirty or forty hulking giants? I intend to do battle with them and slay them. With their spoils we shall begin to be rich for this is a righteous war and the removal of so foul a brood from off the face of the earth is a service God will bless....

**Comment by ajlennon** [comment] 2018-02-17 11:42
If I pop in today how to I get into the staging room to take a look at them @amcewen ?

**Comment by johnmckerrell** [comment] 2018-02-17 11:59
There’s a key on the sharing table, one with big wooden key ring. 

--

**Comment by jackie1050** [comment] 2018-02-17 12:00
Hi Alex - I'm in DoES at the moment, and know where the key is
________________________________

**Comment by ajlennon** [comment] 2018-02-18 11:31
Thanks @johnmckerrell @jackie1050. I will pop in shortly then!

**Comment by amcewen** [comment] 2018-02-18 14:36
For comparison purposes... Sophia's current PC is a Core i5 with 4GB of RAM.  Gerald has a P4 with 2.5GB of RAM.  The Vinyl Cutter PC is an old Shuttle.

**Comment by ajlennon** [comment] 2018-02-18 20:17
I've been through the PCs in the staging area and separated them out into "working" and "have problems".  I think most of the problem PCs can probably be fixed up if the will do to so is there.

In the meantime we have 14 that are OK and 7 that have problems.

Working OK 

Better spec. (4)

Core i3 - 4GB RAM / 500GB HDD (going to use this as the new Gerald-PC). See issue [TBD]
Core i3 -  2GB RAM / 430 GB HDD
Optiplex 380 - Core Duo @ 3GHz / 2GB RAM, 160GB HDD
Core 2 - 4GB RAM 250GB HDD

Middling spec (7)

1 x Optiplex 760 - 2GB RAM, 80GB HDD
6 x Optiplex 755 - 2GB RAM, 80GB HDD

Poor spec (3)

3 x Optiplex 745 - 1,2 GB, 80GB HDD

Non working / Problems (7)

(Of these 3 can probably be fixed easily enough, perhaps by cannibalising drives from the failing systems)

2 x Optiplex 7xx with front plastics missing. Otherwise seem to boot OK
1 x Optiplex BIOS failure, POST beep codes
1 x Optiplex boots but seems to run slow
2 x Optiplex HDD is probably broken
1 x Packard Bell. No power. Replacing the PSU doesn't get it to boot. May be a mainboard/CPU problem

**Comment by ajlennon** [comment] 2018-03-04 19:08
I've updated Gerald and Roland to new hardware based on our standard PC install on the wiki. Seems to be working so am closing this down

**Closed by ajlennon** 2018-03-04 19:08 UTC
Labels: 1 - Must DoES, DoES Move: The Tapestry, help wanted
