### ISSUE TITLE
Make more print for upcoming events

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#129] opened 2015-04-02 16:42 UTC
Building on the business cards should we make more print for the events on the horizon? Flyers to sit around at events on stalls etc unless there's some hidden away somewhere...I can help design if necessary

**Comment by amcewen** [comment] 2015-04-02 16:50
I think this is a duplicate of issue #32 :-)

**Closed by amcewen** 2015-04-02 16:50 UTC
Labels: 2 - The time is now, enhancement, help wanted, question

**Comment by cheapjack** [comment] 2015-04-02 17:00
oh yes, sorry, well closed
