### ISSUE TITLE
Find Out HDMI cable has been damaged and needs repairing

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1199] opened 2019-08-01 09:13 UTC
The plug on the HDMI cable that goes through to the Find Out lab has been damaged. It seems like it is quite fragile but apparently any movement of the TV without unplugging the cable is bad as it pulls on the cable. I'm not sure what the options for repair are but we will need to work out something. I believe @magman2112 did some delicate soldering work in the past.

**Comment by chris-does** [comment] 2019-08-03 13:21
Firstly, please accept my apologies @johnmckerrell if this has been caused by my addressing of #1059.
I am in DoES this morning, and spoke with @amcewen about how I might rectify this issue (regardless of cause).

@amcewen explained that the cable routing from the hole in the wall in Dinky through to wherever the cable is terminated in the Find Out lab may not be straightforward (due to the work in progress sound proofing effort in the lab).

If the provision of a new, robust HDMI cable (nylon braided with strain relief akin to the one I installed to close #1059) can help - please just let me know, and I will provide one accordingly.

Similarly, if I can help with the routing / full installation of such a replacement - I'm only to happy to get involved; though if there is work underway / specific criteria which need to be met, I do not wish to duplicate effort / step on anyone's toes so to speak.

**Comment by johnmckerrell** [comment] 2019-08-03 13:25
Thanks @chris-does, TBH I didn't want to point at your work as I have no idea if that was the cause. I have also poked at the TV recently trying to get a USB stick in it. I think by the time either of us came to this the cable was quite fragile anyway.

I believe @magman2112 is going to take another look at re-soldering the plug on the existing cable early next week.

**Comment by MatthewCroughan** [comment] 2019-08-03 20:32
I've provided them with a Chromecast Ultra to stream their video from the other room, all in all this might actually be a better solution than this clear disaster. It's inevitable that things like this will happen, murphy's law and all. 

The only problem with the Chromecast solution is that the Youtube livestream has a 30~ second latency on it. This might be optimizable by tweaking settings on Find Out's epiphan unit that does the video processing. Also, it may be possible to stream locally on the network which would cut that latency down to around 5s in my experience with RTMP from #927

**Comment by magman2112** [comment] 2019-08-08 14:13
I had a look at the connector on the cable going into the FindOut lab and one of the pins has been pushed in on the connector. I believe this is what is causing the current issue and I wasn't able to pull the bent pin out without doing even more damage to this connector.

I've been doing a bit of google searching and I think I have found a re-wireable connector that can be mounted into a panel in the wall behind the screen. This can then be wired on a shorter cable into the screen and remove the possibility of this cable being damaged again. 

https://cpc.farnell.com/clever-little-box/clb50-hdmi-t/conec2-screwless-hdmi-50mm/dp/AV24303?st=hdmi

I will order one from CPC and should have it tomorrow. I should then be able to fit it in the next few days.

**Comment by magman2112** [comment] 2019-08-18 18:43
I have now installed a wallplate and HDMI socket behind the TV, with the HDMI cable safely terminated in the wall - where it is very unlikely to be damaged again. Ben has supplied a short USB lead to connect from the wall socket to the TV on HDMI 3.

I tested this on Thursday and it appeared to be working OK, so I will close this issue.

**Comment by ajlennon** [comment] 2019-08-18 18:44
I spotted the TV had a Wi-fi mode. Has anybody had this working?

**Closed by magman2112** 2019-08-18 18:43 UTC
Labels: 1 - Must DoES, Broken, Holding out for a hero, Room: Dinky

**Comment by MatthewCroughan** [comment] 2019-08-18 19:08
@ajlennon I provided them with a chromecast to replace that. The "wifi mode" is an unknown implementation of miracast that seemingly only works with my phone, newer android devices remove support for whatever this is, as Ben's phone seems not to see it whereas mine does.

**Comment by ajlennon** [comment] 2019-08-30 11:24
OK it's trivial to connect to the display wirelessly.

- Use the TV remote to cange the source (top left button) to wireless display
- Go to WIndows 10 settings and "connect to wireless display" which will then find the display.

Hey presto

![IMG_5935](https://user-images.githubusercontent.com/1537834/64017281-22388700-cb21-11e9-88ae-6e62f03dbd02.jpg)

**Comment by MatthewCroughan** [comment] 2019-09-01 13:34
@ajlennon I couldn't figure out how to do this with, I find impossible to do on modern android, can you try this on your phone also? This is what Ben wanted to use to cast to it at the time. It's good to know it works in Windows though.

**Comment by MatthewCroughan** [comment] 2019-09-01 13:35
It was Microsoft who implemented the wireless display "standard" wasn't it? It would make sense that it works on a device that supports it.
