### ISSUE TITLE
Paint the doors

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1085] opened 2019-03-19 22:19 UTC
Sound proof room has two coats on the outside, one coat on the inside.

Laser room has one coat on both sides

Dinky needs oil paint cleaning off and the painting.

**Comment by amcewen** [comment] 2019-03-19 23:57
This is a duplicate of #697.  I've copied the comment across to there so it's up to date.

**Closed by amcewen** 2019-03-19 23:57 UTC
Labels: Building, duplicate
