### ISSUE TITLE
Get Harry the Humungous up and running

### ISSUE THREAD

**Issue by KarlDunkerley** [DoESLiverpool/somebody-should#753] opened 2018-04-10 07:49 UTC
We need to get the latest addition to our laser-powered fleet up and running. Here's what I have discovered so far thanks to simeon.diaz@cct-uk.com who supplied the machine originally;

"The price for the software will be £1565 +VAT + delivery. The price includes the software Aps-Ethos V17 and a USB dongle. The software will allow you to create the designs and send them to the cutter.
 
It includes 1 year software support if you find any bugs we will try to resolved them. 
Our software is backwards compatible but the warranty will be limited considering the age of your machine (2004). In the unforeseen event that Aps-Ethos V17 can’t be fixed to work with your machine we will refund you the cost of the software, after receiving the new dongle."

![thumbnail](https://user-images.githubusercontent.com/34492815/38543181-c3de64a0-3c9b-11e8-8851-4611d28a3ac5.jpg)

**Comment by Thingomy** [comment] 2018-04-10 12:11
I like the name.

I regard this price as utterly insane -- especially given the ethos (pun fully intended) of maker spaces. Do we have any experaince of open source (or even other comercial) options?

I would sugest that priorities for selection would need to include:
1) compatible with hardware
2) user friendly and easy to pick up fast given how many users will be involved
3) fully featured (by some definition)
4) reliable (not that the old solution is, given the inkscape compatibiltiy issues to name one)
5) extensable (ie compatible with Sophia and Gerald, should we want to go down that road later)
6) easilly implemented (at the bottom of the list for a reason, I don't expect that to be very liklely)

A quick search identifies: 

LaserGRBL -- Usability wise this isn't great as it reduces us down ot the same workflow that a 3D printer, needs with a separate "slicer" tool. -- I think

Laserweb -- this looks the bomb -- there are some vids on youtube -- uses grbl (or others) on the firmware side, which is fine, but that would mean retrofitting steppers in place of the servoes -- there is liklely a gcode to servo motors firmware option in existance?? -- others around here have more experiance with this than me, so please chip in.

**Comment by goatchurchprime** [comment] 2018-04-10 16:16
https://lightburnsoftware.com/ supports "most GCode and Ruida based controllers.  GCode controllers, including Grbl, Smoothie, and Grbl-LPC, and Ruida controllers, including the RDC6442G, RDC63344, RDLC-320A, and the R5-DSP are among those supported."  

https://github.com/LightBurnSoftware/Documentation/blob/master/DeviceWizard.md

What kind of controllers do we have on Sophia and Gerald?  They're a pretty common sort, and if they're not in the list, it's very unlikely that this one will be.  For obvious reasons, their controller list includes the open source ones (grbl and beaglebone based ones).



One problem is we let plaster dust get into every part of the machinery, it's disgusting.  I found the whole thing uncovered one day and thickly layered.  Possibly all the belts need taking off and washing.  The metal machine tool also got quite a coating as well.

**Comment by amcewen** [comment] 2018-04-11 09:35
This is a duplicate of #607, isn't it?  Can someone merge the useful bits from one into the other and then close one of them (add the `duplicate` label to the one that gets closed for extra credit :-)

I also see that we've already got a `Tool: Laser Cutter - Monster (Morris)` label, which suggests he's already been named?

**Comment by KarlDunkerley** [comment] 2018-04-11 11:31
Have now merged comments into #607. Apologies for confusion.

**Closed** 2018-04-11 11:30 UTC
Labels: 2 - Should DoES, Tool: Laser Cutter - Monster (Morris)

**Comment by amcewen** [comment] 2018-04-11 11:41
No worries, easily sorted.  Just stops the discussion getting split.  Ta!

**Comment by KarlDunkerley** [comment] 2018-04-17 14:52
Adrian, Sean, Julian etc, I've come across a chap called Richard Butler based in prestatyn who is a laser engineer. Had a brief chat with him. I was wondering if we could meet with him to discuss getting Sophia and Gerald back to their peak and then him train us up in routine maintenance so that we can handle most of it ourselves. He's up for it and also has tubes and he can re-gas them. He's free monday morning to come in and discuss things. Would it be okay to go ahead and who could be there? I've told him no promises at this stage. Ps he can also supply controller boards for the lasers to bypass the existing ones which might be useful for Harry the Humungous.Richard's website is Laser Servicing | Training | Consultancy | Technical Assistance and he's also on Facebook.


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Laser Servicing | Training | Consultancy | Technical Assistance

We at RTBTech are able to help with all your technology needs, from buying and selling machines / tools to servi...
 |

 |

 |




What are your thoughts?


Cheers, 

Karl Dunkerley

Mob 07710 353 122

eml karldunkerley@yahoo.com 

    On Wednesday, 11 April 2018, 12:41:34 BST, Adrian McEwen <notifications@github.com> wrote:  
 
 
No worries, easily sorted. Just stops the discussion getting split. Ta!
