### ISSUE TITLE
Kitchen bin ignores me when I wave to it

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#1895] opened 2024-01-17 15:47 UTC
The kitchen bin used to open up when you waved over it.  It hasn't (or hasn't reliably) for a little while now.

The lights on it seem to half-recognise things, so I think it's still getting (some) power, but haven't looked at it further (yet).

**Comment by Robotorium** [comment] 2024-01-17 15:59
Have you considered the possibility that some of your soul has fallen out?

Op wo 17 jan. 2024 15:48 schreef Adrian McEwen ***@***.***>:

**Comment by johnmckerrell** [comment] 2024-01-17 17:23
So I debugged this last week. The problem is that someone is pressing the button to open it but not then pressing the button to close it. If you press the button to close it the hand wavey thing works fine. This is why I stuck a new sticker on it (I forget what I wrote on it now). I'm tempted to just close it but I'll let someone independently verify this first.

**Comment by zarino** [comment] 2024-01-17 17:44
> I'm tempted to just close it but I'll let someone independently verify this first.

Can confirm. I just walked up to it, waved, and nothing happened. I pressed the invisible button (to the right of the lights) a few times (heard a very quiet crunchy motor sound inside the machine each time, not sure why it does that, the lid certainly didn’t open), and from then on, waving above the sensor worked to open the lid (and keep it open if already open).

Pressing the invisible button does seem to have unpredictable results. Sometimes pressing it will make the next wave, or next few waves, not register. Sometimes it doesn’t. I can’t work out whether the number of presses in a row makes a difference – there was no pattern that I could tell. But no sequence of waves and presses from me a few minutes ago could seem to get the bin back into the "broken" state it was when I walked up to it (or when @amcewen first logged this issue). I’m baffled.

Anyway, hopefully the invisible button was indeed the cause of the problem, and @johnmckerrell’s "Wave don’t press" label prevents people pressing the button in future. If not, hopefully they’ll search the issue tracker, and find this issue instead!

**Comment by johnmckerrell** [comment] 2024-01-17 17:47
It sounds like you're describing a single invisible button, my memory is that there's an invisible "open" button on the left and an invisible "close" button on the right but I could well be wrong.

**Closed as completed by johnmckerrell** 2024-01-17 17:47 UTC
Labels: Room: Kitchen, 2 - Should DoES

**Comment by zarino** [comment] 2024-01-17 18:03
Aha! @JackiePease has just explained to me what’s going on.

There are indeed two invisible buttons – an "open" button to the left of the lights, and a "close" button to the right. This explains why, when I was pressing the "close" button, during my comment above, I could hear a crunchy motor sound – this was the (already closed) lid "closing".

Notably, pressing the "open" button keeps the lid open _until the "close" button is pressed._ (Unlike waving, which opens the lid for only a short period of time, after which it closes itself.)

The way to get the bin into a broken state, then, is to press the "open" button to the left of the lights, and then to _manually_ close the lid. At this point, the bin thinks the lid is still open, and so ignores any waving above the sensor, because it expects the lid to be closed at some point by pressing the "close" button. But a human would come up to the bin, see the lid closed, and assume that the wave sensor should work.

Mystery solved.

Not sure how we can prevent this happening, other than, at least, now, a few of us know that, if we find the bin in a broken state, the way to fix it is to press the invisible "close" button to the right of the lights, and then the wave sensor will start working again.

**Comment by amcewen** [comment] 2024-01-17 18:14
Indeed, I was aware of both of the buttons and the waving, but not how it could get into the broken state.  Your sticker hadn't helped @johnmckerrell, it just told me what I already knew about how it was supposed to work :grin: 

Maybe the power issues a while back has trained more people to operate it manually which is why it's getting in that state more often?  Anyway, as @zarino says, more of us now know how to fix it.
