### ISSUE TITLE
Gerald currently incapable of producing straight line engravings

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1348] opened 2019-12-16 06:18 UTC
@DoESLiverpool/laser-maintenance 

@magman2112 had mentioned a while ago that the ball race in the laser head assembly was bad. This is a locally known issue in discussion between me and him. This has prevented me from shipping orders and means I'm £60 down as I may need to issue a refund and has destroyed my material.

![JPEG_20191216_061458](https://user-images.githubusercontent.com/26458780/70883714-cdcfef00-1fcb-11ea-95fd-fa017c31e2fa.jpg)

Here is an example line done at SPEED 200

SPEED 100 improves things slightly, but it is not much better.

It used to be that I could improve things by moving the head position to a less effected region, but this is no longer the case, it happens everywhere.

An unusual friction sound can be heard from the head as it moves across the rail linearly that must be heard in person. It sounds a bit like marbles rolling around a table.

**Comment by magman2112** [comment] 2019-12-17 12:18
I have ordered a new rail and bearings for Gerald, as a similar issue has already been logged on GitHub - see #859.

This is a fairly major repair, so may have to wait till Monty is up and running till we can fit this new rail and bearings.

**Comment by MatthewCroughan** [comment] 2019-12-17 12:21
I'm able to use the laser cutter at Little Sandbox, I've suggested to Rob that he can do the same, so in terms of usage I think we'll both be able to cope for the time being, since this is probably going to take a while to fix.

**Comment by johnmckerrell** [comment] 2019-12-18 13:03
Closing this as it's a duplicate of #859

**Comment by magman2112** [comment] 2019-12-19 15:36
This appears to be a different issue to #859.

I noticed that the 6-axis belt was a little loose, but when I looked at adjusting the tension, it appears that the bearings in the idler wheel for the drive belt had collapsed. On removing the idler wheel assembly, what was left of the bearings fell out into my hand.

Two new bearings will be needed, with the following dimensions.

Outside diameter 15.9mm (Possibly a nominal 16mm)
Shaft size 8mm
Height 4mm

**Comment by magman2112** [comment] 2019-12-19 18:47
With help from Abdullah, we found a Bearing supplier in Liverpool (Bearing Source Ltd in Bootle), and bought 2 replacement bearings. These are now fitted and the belt re-tensioned to a good level. This should hopefully improve this issue, till the new bearings get here.

**Closed by magman2112** 2019-12-19 18:47 UTC
Labels: 1 - Must DoES, Tool: Laser Cutter - Large (Gerald)
