### ISSUE TITLE
Review of flooring

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#696] opened 2018-03-18 17:51 UTC
We should check all the flooring and decide whether any action is required:

- We’ll need some new floorboards in meeting rooms as they were damaged when pulled up for cabling.
- Flooring between the main door and fire escape is in poorer condition than the rest and may need action
- We should vacuum under the floorboards

**Comment by jackie1050** [comment] 2018-03-18 19:04
One of the new floorboards in the co-working space has been put in with its grey painted side upwards

**Comment by johnmckerrell** [comment] 2018-03-24 09:56
Closing this as a duplicate of #696

**Closed by johnmckerrell** 2018-03-24 09:56 UTC
Labels: 1 - Must DoES, DoES Move: The Tapestry
