### ISSUE TITLE
Clarke belt sander

### ISSUE THREAD

**Issue by Knottyashcreative** [DoESLiverpool/somebody-should#1525] opened 2020-11-28 18:16 UTC
Wheels not moving and smoke appeared to come out. Not sure it was from dust or machine. Disconnected plug

**Comment by spironoo** [comment] 2021-11-06 16:06
Seems to be the same issue as #1303

Disc seems to be working now but belt isn't. However, seem to be out of sanding discs.

**Comment by spironoo** [comment] 2021-11-06 16:48
Bought new sandpaper discs, left them in the sanding drawer

**Comment by amcewen** [comment] 2022-05-12 18:40
Agreed, it seems to b a duplicate of #1303.

**Closed as completed by amcewen** 2022-05-12 18:40 UTC
Labels: duplicate, 2 - Should DoES, Tool: Belt Sander
