### ISSUE TITLE
Build a window vent and laser extraction tubing

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#5] opened 2014-08-28 11:32 UTC
I've had a plan to replace one of the small glass panes in the workshop window to permanently fit the laser vents. We have an external vent, and some tubing, but I haven't cut a replacement window pane yet.

**Comment by DefProc** [comment] 2016-09-08 12:20
I found a guide for designing the extraction system: http://www.engraversjournal.com/article.php/2780/index.html

**Comment by DoESsean** [comment] 2017-12-14 10:56
As this will no longer be happening here (a new issue can be opened if it's still needed in the new building) I'm closing this issue.

**Comment by amcewen** [comment] 2018-02-22 13:22
Reopening this as we'll be following the same plan, with a 6" vent fitted in a board of weatherproofed, painted marine ply in place of one of the window panes in the window in the wood workshop.

**Comment by amcewen** [comment] 2018-04-08 22:57
From #692:

@magman2112 has measured the panel - 71cm width x 76cm height

Someone should contact glazing company for price of a UPVC (double-glazed thickness) panel that we can cut a 6" hole in for the vent.

Anyone want to propose what sort of vent we should fit, and how we should plumb both laser extraction tubes to it.  Ideally with part numbers/sources.

**Comment by jackie1050** [comment] 2018-04-10 23:09
I work next to a double glazing factory, so can ask tomorrow or Thursday

**Comment by jackie1050** [comment] 2018-04-30 12:33
I haven't done this yet, but having thought about it, I don't think it would look acceptable from the outside of the building. Would it be possible to cut a hole in the glass instead and fit a collar of some type instead?

**Comment by johnmckerrell** [comment] 2018-05-05 13:25
I don't see that it would look so bad if we manage to do it on one of the panes on the edge. We were wondering if we might even be able to take it through the wall as various other services (like our air con) seem to be going that way.

**Comment by drfraz** [comment] 2018-05-06 10:32
You won't be able to cut a hole in the windows as they are toughened glass so it would shatter & they are double glazed which is likely to be filled with low pressure argon. 
The choices are either a bespoke window or cut a hole in the wall which I imagine would be much cheaper & allow the fitting of a non-return system

**Comment by johnmckerrell** [comment] 2018-05-07 13:04
Would be nice if the fan can be outside. 

--

**Comment by Sean-anotherone** [comment] 2018-11-18 21:19
I suggest that assuming the landlord is content, fitting an external fan and putting a 6" hole through the brickwork to feed it is the way to go.  That way the noise would be much reduced and all 2 (3?) machines could probably share the same fan.

I have a mig welder so if some ca. 2" angle iron can be located I can put a frame together in short order, this could be clad to keep the weather off the fan and fitted with a flap to reduce blow-back if the wind is in the wrong direction.

As for the smoke, the lasers produce a lot less smoke than a coal fire, or domestic woodburner, I don't think there would be an issue.

There would however bee a requirement to fit an inlet vent in the room too.  This needs a bit of thinking about to not result in a cold room.

**Comment by Sean-anotherone** [comment] 2019-01-13 18:37
My understanding is that the plan is to go for a hole in the wall and a common, external fan that can serve to extract all 3 machines?  This does require angle iron (I'll check if there is enough if that frame is available)
This does not however involve going through a window?    - Although, replacing one of the DG units with a painted board and a 90° box to keep it from filling with rain would be a more immediate alternative to heating the whole of central Liverpool.

For the record, the proposed outside box for an extract fan calls for the following :
9mm plywood, painted
rawlbolts - 4 minimum

Angle iron - any size would suffice but it should all be the same ideally
2@ 600mm4@ 550mm
2@ 350mm2@ 364mm

Plus, another 2 at 350, or a couple of strips of 5mm x 40mm ( or similar) plate to bolt the fan onto.

This enclosure is sized for the Gerald fan (so there is most of a spare one available)
Sean

**Comment by Sean-anotherone** [comment] 2019-01-19 00:46
The better choice for material would be some of the table-support legs that are in the alcove - there are more of them and they are box section which will make for a stronger frame.

If these can be confirmed as available I'll chop a few up and build the framework.  A sheet of material to make some covering panels* will be required, and some fixings.

*Could be plywood or OSB if painted before assembly.

I suggest that the priority on this should be to send out feelers to find a 6" hole saw that can get through the wall.  Also, how high above the flat roof is the hole going to be - it really needs to be accessible with a short step ladder at most.

**Comment by amcewen** [comment] 2019-01-22 13:14
We can definitely spare a few table-support legs.  I've labelled the ones from the tables we're planning to chuck with some orange duct tape, but if you'd rather use some of the others then that'll be fine too.

Painting the plywood/OSB should be doable.  I think we should be aiming for something that looks professional and good (not that I think anyone is proposing not to!).

I don't know if @huffeec can shed any light on how Sandbox did the extraction outlet for their laser?

**Comment by Sean-anotherone** [comment] 2019-01-22 18:58
I'll pick up enough legs to build the frame on Thursday, and will probably be able to weld it together over the weekend.
The frame will be (generously)  sized to take the Gerald blower, weatherproof once clad and I would propose just leaving it open at the bottom as the exhaust (or a gravity-flap could be fitted to keep draughts at bay)

**Comment by amcewen** [comment] 2019-04-08 10:19
In case it's useful, Reading hackspace have just been through a similar process and documented their [decision process and extractor fan options](https://wiki.richmondmakerlabs.uk/index.php/Extractor_Fan_Improvement_for_Laser_Cutter).

**Comment by Sean-anotherone** [comment] 2019-04-08 17:27
I have a wind speed meter, Julian will likely have one too (and his won't be 20 yrs old) so we could make similar measurements. I doubt the issues mentioned would be relevant though as we can go through the wall and point the duct anywhere.
Sean

    On Monday, 8 April 2019, 11:19:32 BST, Adrian McEwen <notifications@github.com> wrote:  
 
 
In case it's useful, Reading hackspace have just been through a similar process and documented their decision process and extractor fan options.

**Comment by amcewen** [comment] 2019-04-29 16:24
Sorry, I wasn't completely clear in why I'd included their discussion - it was more for the looking for quiet fans, in case we wanted to find a quieter one :-)

How is this issue coming along?  Wondering whether I need to open a new issue to replace the getting-ever-holier hoses in the current setup or whether this is close enough for us to make do for a bit longer?

**Comment by Sean-anotherone** [comment] 2019-04-29 20:32
I must admit to having been more involved with getting morris working than the extract - I  would propose that once all 3 machines are online that would be the time to fix the extract though.
Sean

    On Monday, 29 April 2019, 17:24:26 BST, Adrian McEwen <notifications@github.com> wrote:  
 
 
Sorry, I wasn't completely clear in why I'd included their discussion - it was more for the looking for quiet fans, in case we wanted to find a quieter one :-)

How is this issue coming along? Wondering whether I need to open a new issue to replace the getting-ever-holier hoses in the current setup or whether this is close enough for us to make do for a bit longer?

**Comment by johnmckerrell** [comment] 2019-05-13 13:30
FYI we've had a (very polite!) complaint from someone living in the building opposite to us saying that the smell of burning plastic is coming in through their open window so it would be good to look at doing something about this. Jason mentioned he knew someone who cuts cores for a living so I've texted that person to see about getting a price. I think Jason suggested it was always about £50. It sounds like we'd need to duct the fumes further away though. Getting height would be difficult, it might be enough to just lead into the middle of the building but I'm sure others will know better than me.

**Comment by DoESsean** [comment] 2019-08-08 10:11
We've had another (very polite!) complaint from the person that @johnmckerrell mentioned above. We need to get this sorted as a matter of urgency, as it's actually affecting the environment around us, and the last thing we want is to be a bad neighbour.

What is needed for us to start progressing this? I know that @magman2112 and @Sean-anotherone  were heading it up, so I'm happy to take their lead. Is it worth also looking into #845 and incorporating @KarlDunkerley into the discussion sooner rather than later?

**Comment by ajlennon** [comment] 2019-08-08 10:19
To be fair I’ve pitched up and the acrid plastic smell has been very noticeable outside the front

**Comment by ajlennon** [comment] 2019-08-08 10:21
Can I suggest we keep the person in the loop so we can see we are taking the complaint seriously and doing something about it? Perhaps even pointing them to this issue?

**Comment by DoESsean** [comment] 2019-08-08 10:22
That seems like a good idea. We've obviously replied to the original email (the latest one only came in yesterday, so I haven't yet), but it would definitely be good to make sure that she knows what is going on.

**Comment by DoESsean** [comment] 2019-08-08 10:25
As a (very) short term panacea, would getting some charcoal filters that could be fitted to the pipe outlet help?

At this point, I'm all for dousing a piece of gauze in Lynx Africa or something and attaching that, so it at least smells like a teenage boy's bedroom rather than acrid plastic.

**Comment by johnmckerrell** [comment] 2019-08-08 10:26
If we’re making suggestions like that I’d probably recommend not directing them to this issue!

**Comment by KarlDunkerley** [comment] 2019-08-08 19:43
Happy to help out. Have some charcoal etc we can use to test out a solution. Away at West Ham this weekend but any evening next week okay.
    On Thursday, 8 August 2019, 11:11:38 BST, Seán Gleeson <notifications@github.com> wrote:  
 
 
We've had another (very polite!) complaint from the person that @johnmckerrell mentioned above. We need to get this sorted as a matter of urgency, as it's actually affecting the environment around us, and the last thing we want is to be a bad neighbour.

What is needed for us to start progressing this? I know that @magman2112 and @Sean-anotherone were heading it up, so I'm happy to take their lead. Is it worth also looking into #845 and incorporating @KarlDunkerley into the discussion sooner rather than later?

**Comment by amcewen** [comment] 2019-09-03 17:09
In #474 (dunno why that wasn't already closed), @magman2112 said:
>A few weeks ago, @Sean-anotherone and I worked through a few websites and came up with a kit of parts we think we will need for a permanent installation for the extractor system.
> 
> The basic idea is to use steel Air Conditioning piping, mounted on the wall just below the windows, which is then routed round the room to a high level mounted fan - which then ducts the exhaust through the gable end wall. All pipes are 150mm in diameter. Flexible pipe will be used to connect the lasers to the piping, with reducers and Y couplings where necessary. We also plan to install a filter box next to the blower, to allow easier cleaning of the exhaust.
> 
> We have chosen to run the exhaust up the gable end wall using one additional 3m length of pipe, as this is about as high as we can reach with a ladder on the outside of the building. We would lileky need a  cherry picker and safety gear to go any higher.
> 
> The shopping list is as follows:
> 
> From DuctStore.co.uk
> 
> 2 x SR 150mm - 3m Lengths Spiral Tube @£18.04 each
> 2 x B90 150mm 90 degree bends @£7.78 each
> 1 x TCP45-150 150mm 45degree T-Piece @£38.60
> 1 x Y45 150mm Y Piece @£10.13
> 1 x RC150 150mm to 100mm Reducer @£5.80
> 1 x FILB 150mm Filter Box @£31.75 (includes 1 filter)
> 1 x EU3 150mm Filter @£4.55
> 6 x SPR150mm Split Ring Supports @£2.45 each
> 12 x BHP-8 M8 Back Plate Threaded Rod Holder @£0.75 each
> 2 x THRD1 M8 studding - 1m Lengths @£1.70 each
> 1 x AFT 50mm Aluminium Foil Tape @£3.04
> 1 x NUT M8 Box of 100 @£2.21
> 5 x HC 60-170mm Hose Clip @£0.94 each
> 
> For the outside parts, we would add the following few items:-
> 
> 1 x SR 150mm - 3m Lengths Spiral Tube @£18.04
> 1 x B90 150mm 90 degree bends @£7.78
> 3 x SPR150mm Split Ring Supports @£2.45 each
> 6 x BHP-8 M8 Back Plate Threaded Rod Holder @£0.75 each
> 2 x THRD1 M8 studding - 1m Lengths @£1.70 each
> 1 x HU 150mm Roof Cowl @£35.78

And @johnmckerrell added:
> I'm fairly sure Jason said we'd be ok running it further along the bottom of the gable wall, i.e. away from Kempston Street in the direction of Constance Street, so if that helps we'd obviously want to keep it in mind when deciding the height to go through. I imagine if there's cutting being done from the outside there might be a different height limit too.

Then @DoESsean ordered a load of parts.  It seems (I haven't checked through the order) that they've turned up...

![Two big parcels, one of ducting, one of other ducting parts](https://pbs.twimg.com/media/EDjhgVTXkAAK6vF?format=jpg&name=small)

![Inside of the box of ducting parts](https://pbs.twimg.com/media/EDjhhCrXoAEvkLi?format=jpg&name=small)

**Comment by Sean-anotherone** [comment] 2019-09-03 17:33
Woohoo!  Will get to use some duct tape, properly, actually on real duct !

More seriously, all the indoor joints will need silicone and the decision to rotate monty or not needs moving up the pile.

**Comment by johnmckerrell** [comment] 2019-09-04 15:05
We had an in-person complaint that led me to send the person who was using the laser cutter home today. Do we have a plan for how we're going to cut the hole in the wall? I imagine that's the main thing that will hold us back now we've got all these parts.

**Comment by johnmckerrell** [comment] 2019-09-04 15:14
I know there was talk about moving Monty, if that can be done great, but for the sake of £20 for some new ducting if we later have to reposition stuff I think prioritising getting the venting done is best (but if Monty can be moved that's absolutely fine!)

**Comment by magman2112** [comment] 2019-09-04 16:55
We don’t have a plan, we just make it up as we go along, obviously.

I was looking to bring a good masonry drill and some long drill bits in to see if we could drill the required hole through the wall, but this was just a discussion with no date set to do this.

We obviously need to give this priority though, so if people don’t mind some noise on Maker night, orwe could likely get this started. We do also have to think what access we have to the roof by the gable end wall and what ladders etc. are going to be needed to fix the external pipe.

**Comment by amcewen** [comment] 2019-09-05 16:56
Getting on the roof isn't much of a problem.  You need to go through the Fashion Hub, and then up the correct staircase and there's a hatch that open out onto the roof.  So  it'd need to be when someone was around in the Fashion Hub, but that's the only restriction (plus what we can get up the staircase I guess - stepladders should be okay, but long ladders might be tricky)

**Comment by johnmckerrell** [comment] 2019-09-05 17:14
Can we compare with Jason about how lose bearing it is. 

--

**Comment by magman2112** [comment] 2019-09-06 14:25
@Sean-anotherone, @KarlDunkerley and I had a look at this issue in detail yesterday. We got access to the roof via the Fashion Hub folks, who were really helpful.

After some measurement of the gable end wall though, we don’t think that a masonry drill is going to be sufficient to make a hole, as the wall appears to 24 to 26 inches thick. If we tried to do this with a masonary drill and chisel, we are likely to cause a lot of damage to the wall, so it looks like a core drill is back in the plans.

We have also had a bit of a rethink about the extraction piping runs, so we may need another length or two of pipe and another one or two 90 degree bends, but we can confirm this one the hole has been made in the wall.

We also confirmed that Morris/Monty can be rotated to allow better access to the machines in the room, but we won’t do this till the hole is made in the wall.

**Comment by seanspotatobusiness** [comment] 2019-09-07 15:53
@johnmckerrel, did you hear back from the contact of Jason who cuts cores for a living?

**Comment by johnmckerrell** [comment] 2019-09-09 15:10
Speaking to Jason last week he did comment that he's hoping to put some artwork on that wall eventually or use it for projecting onto so he would prefer that we don't run the vent up the middle of it, so if we do run towards Constance Street his preference would be to keep it low. We could run it high if we stuck to Kempston Street but obviously we'd struggle to go very high with ladders and I would still worry we'd affect the neighbours

Do we know the type of brick? Also how high off the wall are we looking to go within the room? (Given the above I'm guessing not very)

Assuming it's not engineering brick and not so high off the floor that he needs to bring a "rig" then Jason's guy has suggested £120 to do it and he'll just need a few day's notice. He was quite surprised by the thickness but I concur with your figures, I've pinged Jason to see if he's aware of a cavity or the type of brick.

**Comment by johnmckerrell** [comment] 2019-09-09 15:11
> Can we compare with Jason about how lose bearing it is.

Damn you autocorrect, should've read "Can we compare with Jason about how load bearing it is". I'll do that now also

**Comment by johnmckerrell** [comment] 2019-09-09 15:22
Jason confirms solid to the best of his knowledge, we'll need to do our own RAMS (risk assessment & method statement) on the dangers of being on the roof and we need to be careful not to take any sharp objects that could pierce the new rubber roof.

**Comment by magman2112** [comment] 2019-09-09 16:59
I don't think this wall is engineering brick, at least on the surface - some of the bricks are quite soft. 

We have marked a rough area on the wall where we planned to put the hole with some blue masking tape - basically, between the lines. Although we could potentially lower this a little, we can't take it too low down, as this is the wall we plan to rotate Monty/Morris onto, so we need to leave room for the lid to open.

For working on the roof, we had a look at this the other night and we plan to use a piece of plywood or OSB on the roof below the ladder, with somethink like carpet or a blanket below the board, to reduce the risk of damaging the roof covering.

Once we have the hole in the wall, we can experiment with placing of the exhaust piping a little, using some temporary fixings, to see which provides the best results for the residents on Kempston street. This is the place where we may need another length or two of ducting to give the optimal placement.

Adding @DoESLiverpool/laser-maintenance to this conversation as well.

**Comment by johnmckerrell** [comment] 2019-09-10 11:48
@magman2112 I think the tape fell off the wall. Might be best to use chalk, can you give me an approximate figure for how high off the wall it was just so that I can give the guy a guide? He had said he'd drill from the inside out and I think that will likely make most sense given that the flat roof is so much lower than the floor in the laser room but it might be better to cut into the render.

![IMG_4580](https://user-images.githubusercontent.com/27243/64611419-5174b100-d3c9-11e9-8773-705bd71f9d53.jpg)

**Comment by johnmckerrell** [comment] 2019-09-10 16:15
Hoping that this will happen on Thursday. To confirm we want a hole that we can pass a 150mm/6 inch galvanised steel tube through so that might mean a 7 inch hole. He confirmed he will drill out from the inside and he claimed it won't damage the render. I will be here until 2pm on Thursday but @magman2112 should be around the whole day, just downstairs (@DoESsean will also be around all day). We've marked the wall where we want the hole cut, photos attached.

We will need to clear the area before he begins too, I'll try to remember to look at that tomorrow.




![IMG_4583](https://user-images.githubusercontent.com/27243/64631141-6c0d5100-d3ee-11e9-907a-f04079faa624.jpg)

![IMG_4584](https://user-images.githubusercontent.com/27243/64631168-77607c80-d3ee-11e9-937c-691228da2629.jpg)

**Comment by DoESsean** [comment] 2019-10-31 11:05
Hi all,

We have received the following email from the lady that has previously contacted us about the fumes:

**Hi again Seán,

Any word of progress or dates? I'm becoming more concerned about what kind of health effects this could be causing if any, as I've had to use my reliever inhaler a couple of times this week. 

 I'd left my window a couple inches open (I rescue neglected rats and they need ventilation so I can't  always have it shut :) ) and going to the kitchen, only to return and my room be filled with the smell of burning plastic, and by the time I close up it's too late to avoid my chest being constricted as the smell lingers in the room long after the window is closed. I started to use a charcoal filter dust mask over my mouth and nose in the summer when it was too hot to avoid having my window open all the time, but then I have the animals in my care to be concerned about, who are already unwell due to their backgrounds.

Are the fumes known to be harmful? I know that some cutters can cause a hazard but obviously in this case I have no idea what kind of materials etc are used. I'm anxious and at times upset and concerned for the health of myself and my animals, but I don't know that there's much I can do except continue to follow up the progress, short of speaking with the council. Obviously I don't want to pursue that route as I love what DoES is about, with it being community based and not for profit the last thing you need is the council down your neck. It's a struggle between my health and not causing damage to all the good work you guys are doing. I hope your projects are all going well and I will have to come visit them sometime- I was hoping to pop over to your Repair Café tomorrow with a broken projector I have and some treats but my carer is working a 13 hour shift so unfortunately it will be a miss. Maybe another day, I hope! Will it always be held on Sundays or rotate? 

Cheers as always for your stellar communication and help. I know you're doing all you can and i'm a nark!

Vannah :)** 


She is still being incredibly polite and patient, but I'm not sure how much longer her tether will stretch. I appreciate that I'm not involved in the building of all this, and so my attempting to speed up the people that are, especially since they're volunteering their time to do so, isn't especially helpful, but I do need to make it clear that this needs to be of utmost importance. We are affecting our neighbours in a detrimental manner, and they are, in a very roundabout and polite way, letting us know that they will get the council involved.

With all this in mind, and looking at the calendar, I am advocating that we close the laser room from w/c 10th November (so the Monday after Maker Day) until this is sorted. Obviously, if it's done before that, then there is no problem, but we can't keep negatively impacting the people around us. It kind of goes against our entire ethos.

**Comment by amcewen** [comment] 2019-10-31 15:54
If we're going to close off our laser-cutting provision at the busiest time of the year for most of the people who use it regularly (given the run up to Christmas), we need to do our best to (a) communicate it with them, and (b) make sure we get it fixed ASAP (and so far, neither the person proposing we interrupt our laser-cutting facilities nor those we've been relying on to do the work are in the set of people whose livelihoods will be impacted by it).

I know that anyone relying on the laser-cutters _should_ be following things here, and _should_ be looking to help out with their maintenance, but I'm pretty sure that we aren't doing a good enough job of bringing people into the fold for that.

I'm not saying we shouldn't block out the laser-cutters until this is fixed, but that it's also an opportunity to either (a) draw more people into the pool of talent to keep the space running smoothly, or (b) annoy a bunch of the community.  I'm hoping we can aim for (a) rather than (b)...

**Comment by amcewen** [comment] 2019-10-31 23:33
Tonight @Sean-anotherone and @magman2112, with help from @paulgeering and me, fitted the ducting to the wall round the laser room, and with additional help from @helicalbytes, Rob and Abdullah we rotated Monty by 90&deg; too.

I've ordered these bits we need to finish things off (from Ductstore.co.uk):
 * 1x B90 150mm 90 &deg; bend @£7.78 each
 * 4x SPR150mm Split Ring Supports @£2.45 each
 * 3x BHP-8 M8 Back Plate Threaded Rod Holder @£0.75 each

We still need to buy:
 * 4x M8 wall anchors (expanding anchors) to hold the blower bracket onto the wall, which needs sturdier mounting than the ducting itself.

Next steps:
 * [ ] Tape up the joints on the ducting with the metal duct tape (removing any blue masking tape first)
 * [ ] Modify the bracket that @Sean-anotherone welded up to take the blower, the cut lines have been marked with Sharpie
 * [ ] Cut a piece of wood to act as a floor on the blower bracket
 * [ ] Fix the blower to that with the isolation mounts/feet
 * [ ] Mount blower bracket on the wall
 * [ ] Fit blower and flexible hoses to join them to the ducting and the wall
 * [ ] Connect Gerald and Sophia's extraction to the ducting

That will let us run the extraction system, and just push it out through the wall, and we should get most of that done next #MakerNight (especially if someone can do the first two or three on that list above beforehand)

Then we need to finish off the ducting outside, but that will make most sense to do during the day when it's dry:
 * [ ] Run whatever remaining length of ducting along the outside wall
 * [ ] Fit 90&deg; bend and short section to the cowl to take the last tiny bit vertically

**Comment by zarino** [comment] 2019-11-01 08:55
Well done to @amcewen @magman2112 @Sean-anotherone and @paulgeering for making progress on this last night.

I’m not sure I can help with the more heavy-duty items on the preparation list, but I could have a go at taping up the joints on the ducting, if someone could point me in the direction of the ducting in question, and some metal duct tape.

**Comment by johnmckerrell** [comment] 2019-11-01 22:38
Indeed, well done! Good to see progress on this! I'll take a look at the remaining tasks on Monday to see if I can help with anything.

**Comment by amcewen** [comment] 2019-11-04 14:27
The parts I ordered from ductstore have turned up, I've put it with the rest of the parts (in the big cardboard box by the sewing machines).  We still need to source 4 M8 wall anchors (expanding anchors).

The meta duct tape is in the box of parts by the sewing machines, and each of the joins along the ducting that's fastened to the walls round the laser-cutter room needs a couple of layers of tape over it.

The remaining bits I'm mentioning here are all along the back wall of the laser-cutter room...

The blower bracket is this (it's upside-down in this photo):
![DSC_0216](https://user-images.githubusercontent.com/108468/68127977-d33b1380-ff0e-11e9-96b4-d1f496255fb4.JPG)

The places where it needs modifying (cutting with a hacksaw) are marked in blue Sharpie, you can see one in this photo:
![DSC_0215](https://user-images.githubusercontent.com/108468/68128085-f8c81d00-ff0e-11e9-8a38-5f812d2d048d.JPG)

And I've marked the piece of wood that's earmarked for cutting down to make a floor in the bracket for the blower to sit on - it's this one:
![DSC_0214](https://user-images.githubusercontent.com/108468/68128215-32992380-ff0f-11e9-98ca-7997a1f2c755.JPG)

**Comment by amcewen** [comment] 2019-11-06 11:14
@zarino taped up the joints on the ducting, and @magman2112 got the frame cut down and the wood cut for the floor of the frame.

The floor needs bolting to the frame, and then the blower needs bolting to the floor using the isolation mounts.

**Comment by amcewen** [comment] 2019-11-06 23:23
@magman2112 checked the anchor bolts he's got and they're not long enough.  We need some which can cope with 30mm of frame - [these seem to cope with 59mm of frame](https://www.screwfix.com/p/easyfix-sleeve-anchor-10-x-100mm-m8-10-pack/19292) 

We could also do with some [M8 penny washers](https://www.screwfix.com/p/easyfix-steel-large-flat-washers-m8-x-2mm-100-pack/758ft) too.

**Comment by DoESsean** [comment] 2019-11-07 12:46
I've ordered these for click and collect, John is going to pick them up at
Old Swan (the local one only had the washers), so they'll be with you
tonight.

**Comment by johnmckerrell** [comment] 2019-11-07 17:42
I have them. Intending to bring them in after bed time

**Comment by amcewen** [comment] 2019-11-09 22:27
On Thursday @johnmckerrell, @magman2112 and I got the blower frame fitted to the wall and ready for the blower to be fitted to it.

Today, @magman2112, @helicalbytes and I moved the blower from under Gerald and fitted it to the frame, with some of Gerald's hose run through the wall, and another section of Gerald's hose connecting the blower to the ducting.  The take-off for Monty has a plastic bag fastened over it with a jubilee clip.  The old hose from Gerald to the blower now connects to the ducting, and Sophia's hose is connected to the last part of the ducting.

We should work out a better arrangement for wiring in the blower, but for now it gets plugged into an extension lead that runs onto the frame.  It needs to be plugged in when either of the laser-cutters is in operation.

With the blower now mounted securely on rubber isolation mounts it seems a bit quieter than it used to be (though still pretty noisy), and it does a *much* better job of extracting smoke from Gerald than it used to.

We need to find a dry day one weekend when we can finish fitting the section on the outside.

**Comment by DoESsean** [comment] 2019-11-12 10:07
Thank you, thank you, thank you all for your work on this. I know I've been like a dog with a bone on it, but it genuinely has the potential to make a huge difference - not only to our neighbours, but also to the laser users who hopefully won't have to wear winter coats in there anymore!

**Comment by seanspotatobusiness** [comment] 2019-12-20 12:29
I was wondering how far along the fume extraction got and whether it was
okay to cut acrylic now? I was the one cutting acrylic for a couple of
hours that resulted in an in-person complaint and I was hoping to do
something similar again. Thanks, Sean

**Comment by amcewen** [comment] 2019-12-20 22:32
Hi @seanspotatobusiness, there's still a bit of work to do to get things fully finished, but the extraction is plumbed in enough now that cutting acrylic is okay :+1:

**Comment by seanspotatobusiness** [comment] 2019-12-20 23:29
Thanks, Ardian :)

**Comment by RiverMersey** [comment] 2020-01-21 22:50
Could this thread / issue be closed again now?

**Comment by magman2112** [comment] 2020-01-22 11:05
Not quite, we still need to install the external part of the extractor piping.

**Comment by johnmckerrell** [comment] 2020-01-22 11:07
And then we need to plan for the “ceremonial closing of the ancient issue”. 

--

**Comment by amcewen** [comment] 2020-01-22 11:22
That's what this is being kept for... :-D

![DSC_0420](https://user-images.githubusercontent.com/108468/72890242-65caa200-3d09-11ea-8b27-0ee464fdbae7.JPG)

**Comment by RiverMersey** [comment] 2020-01-22 15:56
@amcewen - or launching the DoES Liverpool ship, or for the DoES Liverpool "Silence of the Lambs" event... :-D

**Comment by magman2112** [comment] 2020-08-30 16:28
@Sean-anotherone, Issac (Sean son) and I fitted the final pieces of the external extraction tubing today. All attached 

So we can finally close this issue.

**Closed by magman2112** 2020-08-30 16:28 UTC
Labels: 2 - Should DoES, DoES Move: The Tapestry, Room: Workshop, enhancement

**Comment by Sean-anotherone** [comment] 2020-08-30 21:11
WooHoo!
Time (finally) to put it in the fridge !
:)


    On Sunday, 30 August 2020, 17:28:23 BST, Mike Gorman <notifications@github.com> wrote:  
 
 


Closed #5.

**Comment by amcewen** [comment] 2020-08-31 09:38
Woohoo! :tada: :100: :clinking_glasses: :champagne: 

Is it true that the Queen arrives on such occasions and closes the issue with the click of a jewel-encrusted mouse button?

**Comment by amcewen** [comment] 2020-08-31 09:43
Having looked at when this was opened, I'm a bit disappointed you didn't manage to fit it on Friday, then it would have been *exactly* six years since it was opened :rofl:
