### ISSUE TITLE
Some replacement furniture

### ISSUE THREAD

**Issue by Sean-anotherone** [DoESLiverpool/somebody-should#1870] opened 2023-10-17 22:29 UTC
I think there was an issue open for this already, but I searched and could not find it, so here's a new one.

My efforts to secure some replacement office furniture from Redgrave Court have come to fruition (finally!)

IN  3 Weeks Time on **Thursday 9th November**  at about 5pm I will be helping to load up a van with :

20 Office desks, grey HDF with built in cable tray, very good quality, These will be in bits for transport.
20 Office chairs - they match the desks.  I sit in one most of the day at work so can vouch for them being pretty comfy.
10 3-drawer pedestals, lockable.
10 3ft roll-front cabinets, lockable
20 sets of desk wiring ( a 4-way that goes in the tray, plus a 2-way "wedge" to sit on the desk.

Hopefully, also a half-dozen 18" high dividers, these go between the desks when they are back to back.

It's all free, apart from the van, which is costing £100 for the two necessary trips. (I'll be asking for that back unless driver can be paid on the day?)

**HELP WILL BE NEEDED TO UNLOAD**

The first trip will be loaded around 5pm on 9th Nov, and should be at the rolller shutter around 5:40 (that's a best-guess)

Second Trip will be as soon as that lot is unloaded

On the day, we'll only need to get the whole lot out of the van and into the downstairs space, at some point it'll need moving upstairs.

The eagle-eyed amongst you may have noticed that the date has changed ( pushed back 3 weeks from the original post), this is because of leave/sick interfering with the ability of the building staff to get this lot dismantled and moved downstairs.  The benefit is that on a Thursday evening there should be more people about to help with the unloading.

They look like this ( without the monitor)
![image](https://github.com/DoESLiverpool/somebody-should/assets/39928682/0b026486-c1db-4a11-bd4c-68c528bb6c2e)

**Comment by Sean-anotherone** [comment] 2023-10-18 17:15
Bumping this to ensure the crowd of willing volunteers note the revised date :)

**Comment by Sean-anotherone** [comment] 2023-11-07 17:54
And it's all looking good to go THIS THURSDAY EVENING.

I'll be helping load the van at around 5pm in Bootle, so the first lot should be at DOES before 6.  

There's pretty much no way that I can do this alone, so **please respond below** if you can be about to help.

At this stage, this is just about getting this stuff out of the van and into the accessible space, not making 50 trips up the stairs in one go!

**Comment by zarino** [comment] 2023-11-09 20:50
The furniture has now been delivered to DoES.

- The 20 desks are in pieces in the Event Room, and need assembling.
- The 20 fancy chairs in the Event Room too.
- The 10 pedestal units and 10 cabinets in the temporary Melodic space downstairs.

Massive thanks to Emma, Gabby, Gary, @helicalbytes, @JackiePease,  @Sean-anotherone, @magman2112, Niel and anyone else I’ve forgotten (!!) for helping unload and carry everything. 🏆 

The desks are 200cm × 80cm – this is 40cm longer than the desks currently in Room 29 (160cm × 80cm). Room 29 is roughly 600cm wide, which means there’s no way that three of the new desks can be laid on end across the room (vertically, in the plans below) with space to walk around or between, as the desks are currently laid out in Room 29.

@JackiePease and I have quickly put together some potential layouts that attempt to retain at least 130cm walking / sitting space between desks:

# A: 16 desks

<img width="1356" alt="Screenshot 2023-11-09 at 20 35 12" src="https://github.com/DoESLiverpool/somebody-should/assets/739624/b0b1f201-8d5a-4956-9b06-7d40e7f48247">

# B: 16 desks

<img width="1357" alt="Screenshot 2023-11-09 at 20 35 28" src="https://github.com/DoESLiverpool/somebody-should/assets/739624/47a44c11-186d-4223-baaa-f72820ebd6ea">

# C: 17 desks

<img width="1357" alt="Screenshot 2023-11-09 at 20 35 43" src="https://github.com/DoESLiverpool/somebody-should/assets/739624/ba64cb75-e698-43e8-b303-bc2b752fa2f7">

All of these layouts would leave 4 spare new desks that could be used elsewhere in the space – most likely in the workshop. But again, these desks are 40cm longer than the white ones in the workshop, so we’ll need to adjust the desk layout to accommodate.

**Comment by Oneill439** [comment] 2023-11-10 15:55
Any thoughts? scaled plans of Room 29 with 18 x Desks with min 1500mm wheelchair turning circle. 1500mm+ between desk space (currently 1400mm) Postion of Desk 16 is questionable and may be best suited for another use.

![Room 29](https://github.com/DoESLiverpool/somebody-should/assets/739624/314119c2-767b-4667-93e3-3960c8a17c3f)

[Room 29 .pdf](https://github.com/DoESLiverpool/somebody-should/files/13321084/Room.29.pdf)

**Comment by zarino** [comment] 2023-11-10 16:20
Thanks @Oneill439 !!

This is almost certainly the most efficient use of the space. Couple of gaps that the existing (or new) cabinets and bookshelves could fit into. Not a square foot wasted ;-)

I like how the desk in position 2 fits _over_ that annoying step next to the window. Efficient.

Also LOL at how my tiny tiny desk (position 5) fits in the gap right in the middle. TBH I’m not massively enthused about having no space near my desk to store things, so what might be fairer is if I replace one of the other positions, somewhere that makes sense – like position 16 (which would also open up a bit more space near the door, but would put me right next to the phone, which is… hmmm) or position 1. A cabinet with a printer, or entry phone, or whatever, could then go in position 5.

**Comment by amcewen** [comment] 2023-11-11 11:24
I like the layouts with some of the desks at 90&deg; to others, but they might not be as efficient and, more importantly, my desk isn't in there so I think those of you working in there should get a greater say on things.

I'm not as sure about using the left-over desks in the main room, given that we've got a matching set at the moment.  Keeping the better chairs and ditching some of the old ones sounds good though.

And I'm enjoying the activity on getting the desks in and working out what to do with them :star_struck:

**Comment by johnmckerrell** [comment] 2023-11-11 15:03
So the last layout does feel a bit "cubicle farm"-esque, but then it also seems to be the layout with the most floor space which might help it to not feel cramped. Are there specific things we should take into account regarding angles of screens to windows? Like would all the desks that have their backs to the windows be basically unusable? (unless we had the blinds down a lot?) Given we'll have to clear the room to replace all the desks maybe there will be chance to try different options although I imagine they'll be quite heavy to lug about! Thanks to everyone who helped to bring them in, apologies I couldn't help!

**Comment by ajlennon** [comment] 2023-11-11 16:30
Hi there. Apologies for lack of involvement but I'm in the middle of renovating my rental property at the moment. 

I am busy tomorrow with Remembrance Sunday commitments but am aiming to be in DoES two or three days in the coming week.

If there is tipping to be done I'm happy to do that... car is an A6 with the seats folding down so whatever can fit in that

**Comment by zarino** [comment] 2023-11-11 17:14
> @johnmckerrell: Are there specific things we should take into account regarding angles of screens to windows? Like would all the desks that have their backs to the windows be basically unusable? (unless we had the blinds down a lot?)

We already need the blinds down a fair bit even with the current "side-on" desk arrangement. But yes, all of the desks with their back to the windows in these drawings will be _particularly_ susceptible to reflections.

I think, if we want more desks "side-on", then we’ll need to drop the total number of desks in the room, which seems like a bad idea.

**Comment by JackiePease** [comment] 2023-11-13 13:08
A couple of other things which have come up in discussion:
- The desks are quite big, and although half a desk might not be enough for most permanent deskers (I don't think it would be for me...), it might be acceptable to hot deskers, who are less likely to have extra screens or a lot of stuff with them - so we could have fewer desks and still fit in more people when it was really busy
- Another use for extra desks could be to replace the workshop desks. Using 4 of the new desks would give 80cm less worktop length, but would look better (at least short term) and give more space to move around there

**Comment by amcewen** [comment] 2023-11-13 16:19
Presumably we can also, though it would be a shame, *not* use (some of) the desks and find someone to pass them on to.

The new chairs are great.  I'm assuming we don't really need *more* chairs, so can mark ones to dispose of from the old ones and then either donate or bin them (depending on their state)?

![image](https://github.com/DoESLiverpool/somebody-should/assets/108468/97f68706-7079-4a18-8992-fc9c1ab95d1c)

Thinking about the additional storage, which is currently down in the old Melodic space (see :point_up:); would it make sense to replace the black desks under the Liverbird with some of the roller-shutter-fronted cabinets?

**Comment by ajlennon** [comment] 2023-11-14 12:01
Just having a look at the plans. Would be a bit worried at facing the window as I doubt I could see anything with the sun in my eyes?

**Comment by ghost** [comment] 2023-11-14 18:00
The Bidston Observatory could absorb leftover chairs, if transport can be arranged.

**Comment by JackiePease** [comment] 2023-11-14 18:17
> Presumably we can also, though it would be a shame, *not* use (some of) the desks and find someone to pass them on to.
> 
> The new chairs are great.  I'm assuming we don't really need *more* chairs, so can mark ones to dispose of from the old ones and then either donate or bin them (depending on their state)?
> 
> ![image](https://github.com/DoESLiverpool/somebody-should/assets/108468/97f68706-7079-4a18-8992-fc9c1ab95d1c)
> 
> Thinking about the additional storage, which is currently down in the old Melodic space (see :point_up:); would it make sense to replace the black desks under the Liverbird with some of the roller-shutter-fronted cabinets?

Seán emptied the old black desks and Alex has taken them to the tip. Julian and Josh have moved in the new cupboards and I've put the stuff back in, although they will need further organisation.

Could be a good idea to do the same where the leaflets table is, if we relocate Fresh, Stale, Last Chance (maybe to on/under the shelf in the Nook) and replace the notice board with one pins go into more easily - perhaps there is a reversible white board type?
![IMG_20231114_181609.jpg](https://github.com/DoESLiverpool/somebody-should/assets/12802256/d1fbb472-d8d3-4d5f-a4a9-8fd5f92df06e)

**Comment by Oneill439** [comment] 2023-11-17 13:49
Hey All, see attached revised plans following some group discussions today. This layout seems to tick most of the boxes but please feel free to share any thoughts...  

[Room 29 - Layout 99.pdf](https://github.com/DoESLiverpool/somebody-should/files/13392474/Room.29.-.Layout.99.pdf)

**Comment by JackiePease** [comment] 2023-11-20 06:52
Update from Sunday:

9 of the desks have now been assembled, and located according to the latest plan by @magman2112 and @Oneill439 with help from some of the Repair Cafe volunteers and others- - I appreciate that this was a lot to ask on a busy Repair Cafe day.

That leaves another 5 desks to assemble, possibly leaving electrics/PAT testing until later, plus relocating the bookcase. 

@Sean-anotherone noted that the pedestal units are very heavy as they contain concrete blocks for stability, so it might be best to leave them downstairs until the lift is working (earliest 18 Dec).

We identified desks and chairs in poor condition to go to the tip. These are currently in the main space and hopefully we will be able to work through taking them away over the next week.

Other desks and furniture that aren 't needed are still in Room 29, the main space and the event space.

Items people have agreed to take so far:
- White 2 desk unit - @johnmckerrell (to be confirmed)
- 2 tall wood effect cupboards - Trevor from Repair Café (to be collected Monday)
- Desk and pedestal unit - @MatthewCroughan (to be collected this week by @goatchurchprime )
- large divider screen - Rachel (to be confirmed - I'll try to contact her again)

**Comment by JackiePease** [comment] 2023-12-03 16:08
The furniture has now mainly in place as per plan 99 above. We realised that we didn't need to move the bookcase, so the 2 roller shutter cupboards are now in the space where that was going to go, and a smaller grey desk has been moved to by the door.
We used 14 of the new desks, so there are 6 still to use/store/pass on.
We also have a few of the old desks left if anyone wants one.

**Comment by JackiePease** [comment] 2023-12-10 17:25
@goatchurchprime and I moved two of the big bookcases into the corner of Room 29 by @johnmckerrell desk.

They will need to be secured for safety if they're going to stay there.
![IMG_20231210_162449.jpg](https://github.com/DoESLiverpool/somebody-should/assets/12802256/cbe3f7bc-cae6-495d-81a0-0e7250bcfe0e)

**Comment by JackiePease** [comment] 2024-10-27 19:40
The new furniture has been in place for quite a while now. There is still a problem in reusing / rehoming a few excess desks but I think we can close this issue.

**Closed as completed** 2024-10-27 19:40 UTC
Labels: help wanted, Room: Room 29, maintenance, Happy To Help, Community, Hack The Space
