### ISSUE TITLE
PC for Sophia won't boot

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1331] opened 2019-11-28 21:37 UTC
The PC for Sophia won't boot from its hard disk. The PC recognises the Hard Disk, but appears to be missing some of its boot files.

**Comment by johnmckerrell** [comment] 2019-11-28 21:45
I was told about this the other day but got distracted and didn't report it, sorry @DoESLiverpool/laser-maintenance !

**Comment by MatthewCroughan** [comment] 2019-11-28 23:06
Will be in soon, as I have to do some cutting in the night. Will try my best to get this fixed.

**Comment by MatthewCroughan** [comment] 2019-11-28 23:10
It's also worth mentioning that we should probably speed up #1127 such that this is less likely to happen in the future.

**Comment by MatthewCroughan** [comment] 2019-11-29 01:59
![image](https://user-images.githubusercontent.com/26458780/69838503-c084d780-124b-11ea-9135-cd78e18a5023.png)

![image](https://user-images.githubusercontent.com/26458780/69838505-c37fc800-124b-11ea-9981-15c647bf7188.png)

This is the relevant output from `dmesg` regarding the state of the hard drive. It's completely and utterly broken, and the kernel is having a hard time handling it, as it even taints the disk module, making future probing impossible until a kernel reboot. It could also be a simple problem with the power cable. Investigating now.

**Comment by MatthewCroughan** [comment] 2019-11-29 02:22
https://cdn.discordapp.com/attachments/336568402447564811/649796182729687040/JPEG_20191129_021755.jpg

The power cable seems fine, so I'm going to have to reinstall Windows and reprovision the laser cutting  software. Though I think the dusty state of the interior really shows that we ought to move towards things like the atomic pi as already mentioned in #1127 so that we can increase the maintainability of the systems in does, if only to satisfy my urge a cleaner, dust-resistant system. 

![image](https://user-images.githubusercontent.com/26458780/69839341-0abb8800-124f-11ea-81cd-d488e132dfe2.png)

In my ideal setup, this would be mounted on the wall, or behind the monitor like a thin client. But this unit is X86, and almost the same spec as the systems we already have, just as capable, just smaller and easier to maintain.

**Comment by MatthewCroughan** [comment] 2019-11-29 04:44
After trying to install Win10 for a bit, it seems like the drive keeps disappearing. I've tested using 2 sata cables on two separate sata controllers on the board, so the likelihood of it being caused by sata are lower.

Instead, I believe it's the molex power connector. I've disconnected the CD/DVD drive and used its sata and power, it seems to be more stable. I'm unsure whether the drive is at fault or if the problem was caused by the power connector, but it seems possible that the installation of windows would have dealt with this issue for a while and eventually broke upon one unfortunate reboot. 

Whatever the case, I'm now attempting to reinstall LaserCut53 from the following source:
https://smokeandmirrors.store/pages/installing-lasercut-5-3-windows-xp-vista-7

**Comment by MatthewCroughan** [comment] 2019-11-29 04:59
I've just discovered that the main reason this PC was having connectivity issues is because the WiFi dongle was often plugged into the front panel USB hub. This hub seems to be flakey, whereas the rear I/O direct to the motherboard is not. The front panel was unable to use the WiFI dongle to submit authentication to a WiFi network, to give you an example of how flakey the connection must be. This isn't worth fixing since we will soon have another system in place of this one.

**Comment by MatthewCroughan** [comment] 2019-11-29 06:56
Windows 10 LTSC is now installed on the Sophia PC, along with the Chocolatey package manager.

From there, I ran `choco install inkscape gimp irfanview mpv googlechrome -y` in order to provision the basic packages the system needs.

Afterwards, I installed Lasercut from the smokeandmirrors source and configured the laser cutter according to the [datasheet](https://www.laserscript.net/wp-content/uploads/2019/02/LS3040-Desktop-Data-Sheet-2019a.pdf)

It is now functional again. I am currently backing up the drive such that it can be restored from this state at a future date if needed.

**Comment by MatthewCroughan** [comment] 2019-11-29 10:51
@DoESLiverpool/directors There's a new samba share I've set up at `smb://samba/does-backups` which now contains `sophia-backup-29-01-2019.img.gz`

This is a compressed backup image of Sophia in a working state as of this morning.

In order to flash it to a drive, do this. Where sdX is the drive id:

`gunzip -c sophia-backup-29-01-2019.img.gz | dd of=/dev/sdX`

Perhaps this can also be done with etcher, to make it such that non tech-savvy users can reprovision the systems.

A very important thing to note is that these images have a shrunk partition, I did this so that the disk image will be done flashing after 19.3GB have been written, this is the minimum disk size required for this Windows image. You need to resize and expand the partition either in Windows via "disk management" or with gparted under Linux, or any other tools in order to complete the job. 

The samba share is public read-only, I can make you accounts and we can move all this data to something that isn't just my server under my desk soon, as I have some 1TB hard drives going spare that we can put in a ZFS array to keep some redundant backup storage in the space that isn't directly tied to me.

**Closed** 2019-11-29 11:28 UTC
Labels: 1 - Must DoES, Broken, Tool: Laser Cutter - Small (Sophia)
