### ISSUE TITLE
Consider a referrals program to encourage more members

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/somebody-should#561] opened 2017-08-24 13:21 UTC
Would something like "first month free" for your friend, and a month free for you, work as a way to have the community encourage new people along?

What would that look like?  What would we offer?  Is it a good idea?

**Comment by DoESsean** [comment] 2017-08-24 13:27
I think a full month free might be a bit much, although I suppose it would
help to get people through the door.

Maybe something like £50 off your first month, and the person who refers
you gets £50 off too, with that repeating every six(?) months, which might
encourage people to stick around. Also, it would mean that if you're smart
and introduced six people at the right times, you could get your bill down
by £50 permanently :)

**Comment by ajlennon** [comment] 2017-08-24 14:52
Maybe a Hunger Games and the more of X, Y, and Z you do the more DoESKarma you build.

Each month everybody's DoESKarma goes into the pot (so the reverse of H.G. where the more you borrow the more tickets go into the draw) and the more you do the more likely you are to win...

Something! Cake or cool tech. stuff or I dunno.

**Comment by SayBeano** [comment] 2017-08-28 15:58
Sounds difficult to administer.

Surely it's easy to credit a newbie's account with workshop/desk days, say 5?
Presumably they're paying membership monthly too?

As for the referrer, I think it's best they get/use something tangible which could link to #68 such as twenty quid preloaded to do what they want with in DoES, or even donate it back to the cause.

**Comment by DoESsean** [comment] 2017-12-21 11:07
Since we're bringing in new pricing, I think this is worth revisiting as part of that.

**Comment by DoESsean** [comment] 2019-10-10 10:24
Closing this issue as it is basically replicated, but more up to date, in #1241

**Closed by DoESsean** 2019-10-10 10:24 UTC
Labels: 2 - Should DoES, Promotion, Team: Organisers, question
