### ISSUE TITLE
Sort out Reward Bricks

### ISSUE THREAD

**Issue by DoESsean** [DoESLiverpool/somebody-should#864] opened 2018-07-31 11:59 UTC
We've been slack with getting the Crowdfunder rewards out, and some of that may be down to the information required being dispersed rather than in one place, so here we go.

* [ ] Agree on size and material for bricks
* [ ] Agree on cutoff date for words and images
* [ ] Find someone who is able and willing to do the lasering
* [ ] Laser bricks
* [ ] Agree on where they will be displayed
* [ ] Put bricks up

We will require 36 smaller bricks and 20 larger, although if the pattern means that there will be blank bricks on the wall, we could look to sell them off at a later date.

**Comment by amcewen** [comment] 2018-08-16 13:26
This is a duplicate of #811, so in the interests of keeping all discussion/progress in one place I'm going to close this.

**Closed by amcewen** 2018-08-16 13:26 UTC
Labels: 1 - Must DoES, Promotion, duplicate
