### ISSUE TITLE
Kitchen Sink 

### ISSUE THREAD

**Issue by jamieisboss** [DoESLiverpool/somebody-should#235] opened 2016-01-05 10:36 UTC
As far as i can tell the trap is upside down and held on with duct tape, meaning waste water has to flow upwards to escape, i can probably fix this, or at least find a proper trap and put that on, does it not leak a lot an occasionally fall apart?

**Comment by ka81** [comment] 2016-01-06 20:08
Kitchen sinks ...LOL ....,

I duct taped it a while back( like a year ago)  after it broke and flooded
the kitchen , Was suppose to be a quick fix as I did say it would need to
be put on properly ( was put together with backwards flow already ...) and
I didn't want to seal it up that way as it needed another pipe really to
flow the right way ?

Although I haven't had chance to don my plumbing uniform since and assumed
soneone had fixed it properlly ...

Caroline :) x

**Comment by DefProc** [comment] 2016-01-08 09:33
I had a look yesterday, and the u-bend does look to be the right way up (exiting upwards), however the flexible pipe that connects to the waste pipe would be expected to run downwards instead of off to the side, this is likely to reduce the flow from the sink

**Comment by amcewen** [comment] 2016-01-08 12:50
The flexible pipe has also drooped, which is what's contributing to the current very slow draining.  It has been held more level with duct tape but that's stopped holding it up at the minute.  (I reattached it over Christmas but it's fallen off again).

I'm wondering if some string round the flexible pipe with the other end held up on one of the screws holding the unit carcass together will work better.

**Comment by DefProc** [comment] 2016-01-12 11:40
I've cleared out the U-bends from both sinks after they stopped draining this morning. It appears to be flowing again now.

**Comment by ka81** [comment] 2016-01-18 17:38
Patrick saviour of sinks ..Lol

**Comment by cheapjack** [comment] 2016-01-25 13:45
Hate to re-open this @DefProc but the main sink is not draining properly. After some plunging Ive managed to get it to drain away eventually but it's not really quick enough to be able to wash up and rinse out the coffee pot very often. Will do another few plunges this afternoon and see if it gets any better and close this again if it does :)

**Comment by amcewen** [comment] 2016-01-28 20:17
Both sinks are draining slowly, so I think the problem is further away from them than the traps.  I've tried a solution of caustic soda and some plunging on them this evening, which hasn't made much difference :-/

**Comment by jamieisboss** [comment] 2016-02-04 19:55
I have a 5m borescope that you can stick down there and have a look if there's a blockage that isnt further then 5m away if you'd like, I'll be in town tomorrow anyway with my laptop so could just pop in

**Comment by jamieisboss** [comment] 2016-04-10 06:39
Sean has brought some of my stuff in and I'm happy to come in one day and have a proper look at this and fix the traps in the kitchen.

I can use the camera to check the first 5m accessible from the sink for blockages, I'll also check the pipe with a spirit level to make sure that there is a reasonably contiguous drop if no one's done that already, then I'd to check the whole pipe over properly for disjointed sections/dents or bends where there shouldn't be. I haven't already checked it end to end so maybe I could find something and be able to figure out a solution without anything more invasive. If i don't find anything then at least that's been done and it can progress, 

I'm happy to bring tools, rods and ppe and have a go at finding the blockage and clearing it. If you want me to I'll go through it with someone so you'd know what to expect, i've done a bit of this before and it's usually more gross than complicated and I've got a decent respirator, mask and gloves so I'll give it go if you want before you go spending money. 

If you'd rather just get a plumber or the building should deal with it, I'm also fine with not putting my hand up pipes and can recommend a reasonably priced, reliable plumber if you don't already have one. 

If it's up to the building, I can at least write an inspection report for you on some appropriate looking paper to give them a kick up the backside and try to help get it fixed as an urgent matter. It genuinely could be something nasty so if its indecipherable from outside after a proper end to end look and level check, and the water still isnt draining consistently a report from an external company might be the ticket; I'll make sure to include some realistic potential causes that imply immediacy would be in someones legal interest so you've got a chance of them fixing it before you don't care at all because it's either a hotel or an english language school.

---------------------------

Or to end on a traditionally silly but possible and possibly interesting note, I'v decided to learn a bit more about robotics and a rover would actually work. An old Raspberry pi, with a couple of different wavelength control mechanisms, lights and camera, I'll risk a few of the 25 or so 18650s ive now gathered, and the motors i got, I've not got any but wheels top and bottom with push out suspension, some wheels must be findable and the suspension could be fabbed with springs and cheap aluminium rod. I'm sure we could make one to fit the pipe and have a gander would be an interesting makernight/makerday, could even add a winch (both ends) and keep going for an explore; the right fishing line can take a lot of weight and you could get 100 or so meters on that rover without too much compromise if im remembering the pipe right. 

I'm thinking Adrian would be shaking his head and saying something about not putting robots in the walls, but if putting sensors on it makes it sensible enough, even getting permission or something, i think it could be liverpool's first amphibious (autonomous?) mobile sensor and definitely deserves to be a thing on the things network, though I'm pretty much 100% that I'm using a different definition of thing, the swamp thing one. Why not both though?  Prowling the sewers, sensing methane, fighting crime (mostly illegal chemical disposal practises), maybe underground mapping? there's all kinds down there according to the people at the williamson tunnels...

Im not sure how serious i am, I started joking, then thought of some actual use cases, and i genuinely do want to make a robot.

**Comment by jamieisboss** [comment] 2016-04-10 07:14
I'm self assigning the top bit, about the kitchen and pipe, Ill come and check it over, fix the sink pipes with solvent weld and scope the bit i can scope.

I'm not sure whether to move swampthing into #272 it is applicable here, and not actually a terrible idea if not overcomplicated as above, something simple with lights, camera and forward action, anchored in the kitchen so it  cant go too far could actually be the least invasive way of getting a view further down if the  5m is fruitless, guess wait and see if the 5m scope gives an answer.

**Comment by jamieisboss** [comment] 2016-05-13 12:49
Someone needs to sign off on me fixing this or not fixing it and Sean's in Vegas, I'll need new respirator filters and some pipe and push fit connectors 

so 
a set of these: http://www.screwfix.com/p/3m-6059-reusable-respiratory-filters-abek1-2-pack/9662g
and i'll get a couple of lengths of pipe 9in case one goes wrong somehow and some connectors  and wall clips

1x 3m 15mm pipe 
1  http://www.screwfix.com/p/jg-speedfit-pem0315w-elbow-15mm-pack-of-10/57953

2x http://www.screwfix.com/p/solvent-weld-waste-pipe-40mm-x-3m-white/44310
1x http://www.screwfix.com/p/floplast-straight-coupler-white-40mm-pack-of-5/58998
1x http://www.screwfix.com/p/floplast-pipe-clip-40mm-pack-of-10/18926
1 http://www.screwfix.com/p/mcalpine-flexcon2-40mm-flexible-connector-white-pack-of-1/43713 (in case there's a weird angle or through a wall is weird o something

It should all be 40mm waste i think; but i don't think it is so i'lll measure it again tomorrow because i forgot what it was and get the right size.

If someone says go for it and orders that stuff, i'll sort the kitchen but without the proper drop it'll never be right right, but then you're moving so i guess just not having 6 month old muck flowing back into the sink is good enough for the time being, I'll try and get the drop as steep as possible in the kitchen to evacuate the water from there and give it a bit of force. . 

Anyway, all I'm witing on is a yes or no, to go for it or not,. If not I'll butt out and leave you to it, but until someone tells me either way I cant shut up or do it

**Closed** 2016-06-04 12:33 UTC
Labels: 2 - The time is now, bug, Kitchen, wontfix
