### ISSUE TITLE
Gerald has not enough power to cut and the laser focus seems to be distorted

### ISSUE THREAD

**Issue by FatihDeveci** [DoESLiverpool/somebody-should#1609] opened 2021-08-31 15:36 UTC
In short, the laser power is not enough to cut. Gerald's new red light looks weaker than usual. The laser's red light appears as a line rather than a dot. For this reason it sometimes cuts double. I have tested it by cutting some small circles. Please see the attached photos.

While cutting cardboard with Gerald as usual, after a point I realized that he was drawing instead of cutting. When I checked, the newly installed red light was not visible. When I turned Gerald off and on, the light came on but was weak. It may also be related to the position of the laser head after turning off and on again. I think there was a problem when the drawing layer was finished and the cutting layer was starting. The problem may be in the mirror. On the other hand, there may be a problem at the exit from the laser tube.

![IMG_20210831_153656](https://user-images.githubusercontent.com/72569224/131531843-5501dc1a-4e80-4e37-b5a6-fa7eecc90749.jpg)
![IMG_20210831_153837](https://user-images.githubusercontent.com/72569224/131531816-df0d87f1-28a9-48b3-a73e-7aadb46bc4a2.jpg)
![IMG_20210831_153718](https://user-images.githubusercontent.com/72569224/131531834-a6bc1065-f692-484f-8763-6ea51f38a2db.jpg)

**Comment by magman2112** [comment] 2021-09-01 18:15
I've had a look at Gerald and have confirmed that there is an issue with the laser alignment on the left hand side.

I suspect this has something to do with the mounting for the first mirror, next to the laser tube. When @Sean-anotherone and I last aligned this, we were pretty much on the limits of adjustment for this mirror.

As Sean and I are most likely in for Maker Night tomorrow night, I have an idea for an improved mount for this mirror that we should be able to make on the night. We will then undertake a complete re-alignment on Gerald.

Added Laser Maintenance team tag @DoESLiverpool/laser-maintenance

**Comment by magman2112** [comment] 2021-09-06 08:06
Sean and I spent a lot of time on Gerald on Thursday night, without resolving the issues.

Part of the problem is the lack of adjustability with the laser tube mounts. Sean and I think we can improve this by using mounts similar to those we bought for Tony. I just need to identify the right ones to fit Gerald, as well as leaving options for different laser tubes to be fitted to Gerald in the future.

**Comment by magman2112** [comment] 2021-09-12 09:00
I spent some more time on Gerald on Saturday and managed to significantly improve the performance of the laser across the whole bed.

The current setup is still not perfect, there is a section of the bed towards the top right where you get double images (the beam catches the air assist novel, causing a poor cut). But the key area’s of the left half and front half of the bed is cutting well, so 80-85% of the bed should be useable.

I’m going to leave this issue open for now, to see if we can improve the setup further on a subsequent attempt, but I am going to remove the broken label for now.

**Comment by amcewen** [comment] 2022-04-21 18:49
Given the major upgrade happening inn #1642, I think we can close this.

**Closed as completed by amcewen** 2022-04-21 18:49 UTC
Labels: Tool: Laser Cutter - Large (Gerald), 2 - Should DoES
