### ISSUE TITLE
Design and build a new carriage for sophia

### ISSUE THREAD

**Issue by magman2112** [DoESLiverpool/somebody-should#1516] opened 2020-11-02 09:49 UTC
As noted in #1508, the carriage on Sophia has been much modified and currently limits the x-axis travel due to parts catching the chassis.

I think we should design a brand new carriage that uses v-wheels and allows full travel on the axis as well as limit switches on the travel. We can then CNC cut this from a block of aluminium on the CNC machine.

I will look at doing some initial CAD work, using the existing carriage as a model, but I would also appreciate any thoughts, comments or wishes for improvements we can possibly include in this re-design.

**Comment by MatthewCroughan** [comment] 2020-11-02 09:52
My immediate comment is that when Sophia is done with, it's going to be like Trigger's Broom from Only Fools and Horses. 17 new carriages and 14 new chassis. :smile:

**Comment by amcewen** [comment] 2020-11-03 22:44
This is a duplicate of #1143 isn't it?  I've copied your initial comment across @magman2112

**Closed as completed by amcewen** 2020-11-03 22:44 UTC
Labels: duplicate, Tool: Laser Cutter - Small (Sophia), 2 - Should DoES

**Comment by fauxchains** [comment] 2023-05-23 00:38
May I please request granting any and all old unused and defunct parts to older model designs for further development? Ajh 553 county road 3016 Dayton TX 77535
