### ISSUE TITLE
Unable to save simple Inkscape drawing as dxf on laser PC

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1462] opened 2020-07-03 18:00 UTC
I created a simple drawing consisting of 2 concentric circles, using the Gerald's PC. When I tried to save it as a dxf I got a Python error.

**Comment by MatthewCroughan** [comment] 2020-10-08 13:40
This is why we should have stateless Windows systems that just reset to their known good state when they reboot. People can save things on Samba, but the PC will be entirely reset to its working state once it reboots. This saves a lot of hassle and will entirely eliminate issues like this. At the very least, it will make them solvable and less vague, since the issue will be reproducible.

This is how real world tech companies run their businesses, because it massively reduces headache and helpdesk complaints about infrastructure.

That said, can we close this now? I have saved a DXF fine on that computer many times since this issue was listed.

**Comment by MatthewCroughan** [comment] 2020-10-11 12:39
This issue was occuring on Gerald's system.

When @Sean-anotherone tried to open a dxf, he ran into what I think was this issue. We noticed that inkscape was outdated so removed it and added inkscape with the chocolatey package manager for Windows with

`choco install inkscape`

We should now manage this installation with chocolatey and upgrade it like this.

`choco upgrade inkscape`

The issue has been resolved by having reinstalled inkscape in this manner, as dxfs can now be saved without issue.

**Closed as completed by MatthewCroughan** 2020-10-11 12:39 UTC
Labels: Tool: Laser Cutter - Large (Gerald), 2 - Should DoES
