### ISSUE TITLE
Gerald is jumping along the y axis

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/somebody-should#429] opened 2017-01-19 23:00 UTC
At make night Gerald was working fine for most of the evening,
In the last hour it started jumping along the y axis, in use and setup. 

We had a look and the belts don't seem to be lose, and there wasn't anything else obviously wrong.

As it is it's unusable.

**Comment by amcewen** [comment] 2017-01-20 11:04
I think (I'll reopen this if there are more reports of problems with him today) that this is a duplicate of #287.  The remaining screw for the shim had worked loose again, so I've re-tightened it.

**Closed by amcewen** 2017-01-20 11:04 UTC
Labels: 1 - You're all I need to get by, duplicate, Gerald the Gigantic Laser Cutter, Workshop
