### ISSUE TITLE
Upgrade the vinyl cutter/sublimation printer computer 

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#1001] opened 2018-12-11 10:59 UTC
This is waaaaay too slow and unresponsive.  Even the browser keeps crashing and the ethernet card is broken (so it uses a wifi dongle).  

It's not in a state where we can select cut vinyl icons for visitors in a reasonable time.  

(Assigned to @MatthewCroughan who worked wonders with the CNC machine, and one of those boxes could be recycled to this job, perhaps.)

**Comment by johnmckerrell** [comment] 2018-12-11 11:01
Feels like a duplicate of #990

**Comment by MatthewCroughan** [comment] 2018-12-11 18:52
Agreed @johnmckerrell, the next upgrade should be one that revamps the entire setup rather than redundantly using an overpowered machine for the job.

All we need is a raspberry pi and some time. Not to have a needlessly bulky machine for this job.

**Closed by MatthewCroughan** 2018-12-11 18:52 UTC
Labels: Tool: Sublimation Printer (Bella), Tool: Vinyl Cutter & Plotter (Harry Plotter), Tool: Vinyl Cutter & Plotter (Roland Rat)

**Comment by ajlennon** [comment] 2018-12-11 18:58
Why don't you get the RPi going @MatthewCroughan and when you're done we can compare the two side by side and decide what is best?

**Comment by MatthewCroughan** [comment] 2018-12-11 19:01
@ajlennon I'll get it going maybe tonight, the reason for not going ahead with it is included in #990. 

Mainly that I don't want to nuke the existing setup overnight like I did with the CNC room since it is so readily used. I'll experiment lots with wine on a pi to see if it's possible to use the existing software too.

Do you have a spare pi I can get going with?

**Comment by ajlennon** [comment] 2018-12-11 19:03
Nothing spare at the moment. 

For me it would be a "really bad"(tm) idea to change what is currently working (badly) without having a better solution in place that is agreed upon...

So that's why I suggest you "show us the code" :)

**Comment by MatthewCroughan** [comment] 2018-12-11 19:05
@ajlennon I'd be using other people's code. It's just software configuration, I'm not replacing anything overnight as I stressed in #990

**Comment by ajlennon** [comment] 2018-12-11 19:05
Yeah - easy job :) Give me a shout when  you have it working!

**Comment by ajlennon** [comment] 2018-12-11 19:06
But I'll emphasise that for me I hope you'll get it all working and show it around before you replace what is currently there?

**Comment by MatthewCroughan** [comment] 2018-12-11 19:07
_"There is no interest in removing the old setup immediately, but I am interested in getting it to work in a way that replicates what we currently have set up and then phasing the old aging system out. Anything that breaks the user experience, or even modifies it in a way that people are uncomfortable with is a no-go."_

#990

**Comment by ajlennon** [comment] 2018-12-11 19:07
Great - I can't wait to see what you come up with!
