### ISSUE TITLE
Fire in Gerald

### ISSUE THREAD

**Issue by mohnyb** [DoESLiverpool/somebody-should#1869] opened 2023-10-17 14:11 UTC
Please make your issue:
Whilst laser cutting a price of 3mm acrylic the material caught fire and caused damage to the laser feeder cable and wiring on the bed. This happened at 15.00 on 17 Oct

**Comment by JackiePease** [comment] 2023-10-17 14:25
@DoESLiverpool/laser-maintenance I've phoned @magman2112 , who is hoping to get in this evening 

![IMG_20231017_152346.jpg](https://github.com/DoESLiverpool/somebody-should/assets/12802256/722f87d9-9e86-4ada-a2b1-aa7767832591)

![IMG_20231017_152331.jpg](https://github.com/DoESLiverpool/somebody-should/assets/12802256/79020e7b-63a8-40b6-8b79-e2dcbbf1677c)

**Comment by magman2112** [comment] 2023-10-17 14:32
There is quite a bit of work needed to repair this, though it looks like the sensors themselves haven’t been damaged.

one concern though is the possibility that the inputs on the control board could have been damaged.

I will pop in this evening to see what I can do about a repair.

**Comment by amcewen** [comment] 2023-10-17 15:45
Thanks for reporting it @mohnyb.  I've flagged it as `broken` so anyone checking knows it's out of order.

**Comment by magman2112** [comment] 2023-10-17 19:42
An overview of the issues with Gerald after it’s latest fire are as follows:

1. Wiring to limit switches on carriage burnt through. 
2. Drag chain missing a section
3. Air assist pipe melted and missing a section
4. Drive belt was badly damaged and broke after a few movements.

We had a new Drag chain in stack, so this has already been replaced.

The limit switches weren’t damaged, just the wiring. I am going to repair this tonight, so we have less to repair when the other issues are addressed.

We don’t appear to have any of the drive belts left in stock (or we have finally used up what was bought years ago). Measuring the drive belt it is 15mm width with a pitch of approx 2mm. The only labelling on the belt is “MXL” which appears to be a belt type  with an imperial pitch measurement of 0.08”, or 2.032mm.

Mostly belts of the correct pitch and width are closed loops. I have found a few suppliers in China who have this in stock - including Cloudray, but delivery is typically 2 weeks.

I found one supplier in the UK on eBay that has a 2mm pitch belt in stock, which should work in our application till we can get the correct belts, I suggest that we get 5m of this belt then choose a supplier to get a proper MXL style belt and get 10m of this belt for the laser spares cupboard.

https://www.ebay.co.uk/itm/284184122097

We don’t appear to have any more of the silicone air assist tubing in stock, so we need to buy some more of this as well. It appears to be 5mm internal diameter with a 9mm external diameter at present, though I would like to use a thinner wall tubing to make it easier to fit in the drag chain and reduce the moving resistance to bending. 

I found something suitable on Amazon which has quick delivery, as follows:

https://www.amazon.co.uk/Silicone-Meters-LAVMHAB-Flexible-Rubber/dp/B0C57ZMQ8K/ref=sr_1_1_sspa?crid=9HSZ01DT05BY&keywords=silicone%2Btube%2B5mm%2Bid&qid=1697572451&sprefix=silicon%2Btube%2B5mm%2Bid%2Caps%2C133&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1

**Comment by mohnyb** [comment] 2023-10-18 12:54
Hi folks, do you want me to order and pay for the item on eBay as it did happen on my watch. I can order the 5m belt and have it delivered to an appropriate address, Mo. Sent from my iPhoneOn 17 Oct 2023, at 20:43, Mike Gorman ***@***.***> wrote:﻿
An overview of the issues with Gerald after it’s latest fire are as follows:

Wiring to limit switches on carriage burnt through.
Drag chain missing a section
Air assist pipe melted and missing a section
Drive belt was badly damaged and broke after a few movements.

We had a new Drag chain in stack, so this has already been replaced.
The limit switches weren’t damaged, just the wiring. I am going to repair this tonight, so we have less to repair when the other issues are addressed.
We don’t appear to have any of the drive belts left in stock (or we have finally used up what was bought years ago). Measuring the drive belt it is 15mm width with a pitch of approx 2mm. The only labelling on the belt is “MXL” which appears to be a belt type  with an imperial pitch measurement of 0.08”, or 2.032mm.
Mostly belts of the correct pitch and width are closed loops. I have found a few suppliers in China who have this in stock - including Cloudray, but delivery is typically 2 weeks.
I found one supplier in the UK on eBay that has a 2mm pitch belt in stock, which should work in our application till we can get the correct belts, I suggest that we get 5m of this belt then choose a supplier to get a proper MXL style belt and get 10m of this belt for the laser spares cupboard.
https://www.ebay.co.uk/itm/284184122097

**Comment by JackiePease** [comment] 2023-10-18 13:13
I have ordered the 2mm pitch belt, should arrive by 21 Oct

**Comment by johnmckerrell** [comment] 2023-10-18 14:17
I've ordered the air assist tube, should turn up tomorrow.

**Comment by magman2112** [comment] 2023-10-18 15:19
Although the items I have identified in my earlier comment should get Gerald working again. I still think we should get the correct belt for the pulleys, which is the MXL version.

I have found a few suppliers, all in China so far, the cheapest being Cloudray, as follows:

https://www.cloudraylaser.com/products/cloudray-mxl-5-15m-open-ended-timing-belt?variant=12877198393395

choosing the 15mm width from the drop down list for this item.This costs $6 per metre, there will be shipping and import duty to pay, it this is still cheaper than any other sources I have found so far.

 I would recommend getting at least 7m of this belt, so we have spares for both the x and y axis on Gerald which we can then keep in stock.

Delivery is approx. 7 days, hence why I chose the non MXL style belt to get Gerald up and running sooner.

**Comment by magman2112** [comment] 2023-10-18 15:29
@mohnyb i would say that this is not something you should worry about. This is just part of working with a laser cutter and we typically have one or two small fires a year. We often have spares on hand to make the repairs, it’s just we didn’t replenish some spares after the last maintenance repair.

I suspect that part of the problem is keeping the bed clean, as deposits on the bed are often a contributing factor to small fires. With clear acrylic, you can often see the flames as you cut. 

I am looking into a possible new policy that we ask users to clean the bed after they have used it, now that we have found a good cleaning solution. This policy is still to be agreed though, plus the whole bed needs a deep clean before we could instigate such a policy.

**Comment by johnmckerrell** [comment] 2023-10-20 10:37
The air assist tube turned up. I've stolen a small section for a soap dispenser, I hope that doesn't cause problems! The rest is in the cupboard in the laser room.

**Comment by magman2112** [comment] 2023-10-21 23:39
@JackiePease advised me that the drive belt had arrived so I fitted this and the new air assist tube on Saturday evening.

I also had to lubricate the bearing, as this was sticking - the heat probably melted the grease in the ball race. We will need to check this in a few days to see if this is still OK. The drive belt will likely need adjusting in the near future, something to be checked on Maker Night methinks.

As I had to remove the laser head to lubricate the ball race, I did an initial alignment which looks to be working well. I also removed and cleaned the mirror on the laser head and re-aligned this as well.

I also cleaned the bulk of the debris from the bed and cleaned up some of the debris from the bed.

Whilst test cutting, I noticed that the extraction wasn’t working very well, then I remembered that I hadn’t closed off the extractor pipe that used to go to Sheila, when this laser was moved down stairs. With 20:20 hindsight, this could have been a contributing factor to the fire, as the extraction was quite weak. I have taped over this section of the extraction pipe and extraction is now actually better than when Shiela was connected.

During testing, I also noticed that the bed is out of level again, something else to be attended to on Maker Night.

I have removed the broken label, but will leave this issue open till we complete the last few adjustments.

It might also be worth letting users know that with the latest cleaning, Gerald is a bit more powerful at present, so cutting speeds may need to be increased to compensate.

**Comment by seanspotatobusiness** [comment] 2023-10-22 23:01
You know those small automatic extinguishers? Would they be too slow
to activate to prevent this kind of damage? Maybe they wouldn't be
effective anyway with the extractor on. IDK.

**Comment by JackiePease** [comment] 2024-01-11 18:50
I have ordered 10m of belt from Cloudray for $97 inc. VAT

**Comment by JackiePease** [comment] 2024-01-18 14:02
This has arrived - I've put it in the laser spares cupboard

**Comment by magman2112** [comment] 2024-05-02 19:28
The new belt has been fitted, so I’m going to close this issue as the last to-do item from the fire is now completed.

**Closed as completed by magman2112** 2024-05-02 19:28 UTC
Labels: Tool: Laser Cutter - Large (Gerald), Shopping, 1 - Must DoES
