### ISSUE TITLE
Replace one window pane with panel to allow extraction for laser cutters

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#692] opened 2018-03-18 17:24 UTC
@magman2112 has measured the panel - 71cm width x 76cm height

Someone should contact glazing company for price

**Comment by johnmckerrell** [comment] 2018-03-18 17:27
If you mean the glazing company would remove the glass - Dave has said he can do this for us, we'll obviously have to prepare the panel in advance for him. I wonder if any of the stickers on the windows will give us the exact dimensions, if not we might be able to get from Jason.

**Comment by amcewen** [comment] 2018-03-20 21:38
There was suggestion that we should get a double-glazing firm to cut us a panel of whatever sort of stuff they use for UPVC doors, etc. as that'll be the right thickness, etc. to replace the glass.  Rather than getting one to come fit it for us, we were assuming Dave would be doing that bit.

**Comment by amcewen** [comment] 2018-04-08 22:57
This is a duplicate of #5, so I've copied the relevant bits over to there.

**Closed by amcewen** 2018-04-08 22:57 UTC
Labels: DoES Move - Settling In, Room: Workshop, Tool: Laser Cutter - Large (Gerald), duplicate
