### ISSUE TITLE
doesliverpool.com server needs rebooting occasionally and only @OddEssay has access.

### ISSUE THREAD

**Issue by OddEssay** [DoESLiverpool/somebody-should#273] opened 2016-04-11 12:32 UTC
Right now, doesliverpool.com needs to be rebooted every couple of weeks because the site is down. 

In addition to this, the only person with access to the VPS management panel is @OddEssay.

It would make sense to migrate to a VPS that everyone has access too or a hosted version of WordPress where no one needs to worry about maintenance issues.

**Comment by madjake45** [comment] 2016-04-11 12:34
We know the vps requirements for this as I should be able to give a vps
just for the does site

On Mon, Apr 11, 2016 at 1:32 PM, Paul Bennett-Freeman <
notifications@github.com> wrote:

> Right now, doesliverpool.com needs to be rebooted every couple of weeks
> because the site is down.
>
> In addition to this, the only person with access to the VPS management
> panel is @OddEssay <https://github.com/OddEssay>.
>
> It would make sense to migrate to a VPS that everyone has access too or a
> hosted version of WordPress where no one needs to worry about maintenance
> issues.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/DoESLiverpool/somebody-should/issues/273>
>



-- 
-------
Jake

**Comment by OddEssay** [comment] 2016-04-11 14:42
This is just a straight forward WordPress install.

Digital Ocean's basic $5 per month server runs multiple WP installs happily -https://m.do.co/c/a9c69c6eb29f link gives $10 of credit, so two months on that package.

Digital Ocean also do one-click installs for WordPress, but that needs the second level image to run (More to do with the image they use to install, rather than running requirements) which would run at $10 per month.

Both options are cheap, offer more than enough resources (I use them for all my personal, and professional hosting these days), and would be easy to add multiple users too as they use standard installs.

**Comment by shrkey** [comment] 2016-04-11 14:50
Those are EX-VAT prices - https://www.digitalocean.com/help/pricing-and-billing/tax-help-eu/ so don't forget to add your 20% :)

**Comment by madjake45** [comment] 2016-04-11 14:53
Well I have snet @OddEssay some login details to a $5 droplet which does can do with as they please

**Comment by OddEssay** [comment] 2016-04-11 14:59
@madjake45 Cheers - I'll take a look this evening.

As a stop gap, I've made sure I've got today's backups on my laptop as a contingency.

**Comment by madjake45** [comment] 2016-04-11 14:59
I went down the route of paying the extra $1 a month for weekly backups as
well

On Mon, Apr 11, 2016 at 3:59 PM, Paul Bennett-Freeman <
notifications@github.com> wrote:

> @madjake45 <https://github.com/madjake45> Cheers - I'll take a look this
> evening.
>
> As a stop gap, I've made sure I've got today's backups on my laptop as a
> contingency.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/DoESLiverpool/somebody-should/issues/273#issuecomment-208386067>
>



-- 
-------
Jake

**Comment by amcewen** [comment] 2016-04-13 09:31
Thanks for the offer @madjake45 (and just running with things!), but given issue #18, if we're migrating the website to a different server I think it'd make sense for it to be one that @DoESLiverpool has control over, even if it costs us ~$5/month.  Just so we don't end up in this situation again where one person is a potential-point-of-failure or the only one who can fix things :-)

**Comment by madjake45** [comment] 2016-04-13 09:43
:cry:

**Comment by DefProc** [comment] 2016-04-13 10:47
Does this need something more than DoES provisioning a VPN so that Jake can deploy?

**Comment by madjake45** [comment] 2016-04-15 11:56
Well I currently only handle http://github.com/DoESLiverpool/status which is on my server at the moment and feel it's probably the best idea to keep it off the same vps as the main website

**Comment by amcewen** [comment] 2016-04-18 10:28
I think it needs @OddEssay to do the deploy, initially at least?  Presumably setting up an account for hello@doesliverpool.com on the way?

The website is down again at the minute (has been since yesterday at least) :-(

@OddEssay let us know what else we can do to help out in migrating it over

**Comment by jamieisboss** [comment] 2016-04-19 23:51
I haven't had much chance to work on the new site for a while but should do soon, question about the hosting, kind of, does the site need to be based on wordpress?the core wordpress functionality has been replaced by weeknotes and in as far as I can see, anything else whizzy is an embed or managed offsite. 

If you got away without wordpress, generating the site statically, you could put it in an aws s3 bucket, delivered through cloudfront and add cloudflare with the always online feature, and still probably pay less than a fiver. (if we did the cloudflare bit as it's $20/month for the first pro Account of then $5 to add extra ones, we've already got a few so you could get away with just the $5 I daresay. 

The site would be considerably more secure, fast, robust and basically impossible to go offline by single failure, as you'd have added 4 types of redundancy as well as an intelligent managed Web application firewall. 

I like wordpress but if you aren't using the features, then it's an unnecessary overhead and the static site in a bucket method allows you to easily trigger lambda events or have them triggered from elsewhere, which opens up a new world of possibilities for the site generally

**Comment by amcewen** [comment] 2016-04-20 09:48
I don't think we're particularly wedded to Wordpress, *but* we are wedded to having a site available for people to use :-) so it feels to me that migrating the existing site to a new server is going to be the quickest way to fix the short-term issue.  Moving away from Wordpress can then be part of #19

**Comment by jamieisboss** [comment] 2016-04-24 03:57
Ok, Cool, that'll probably speed the dev a quite a bit, (unless it doesn't)

**Comment by amcewen** [comment] 2016-04-25 11:23
The website is down again... @OddEssay any chance you can stick the backups somewhere and we'll work out what to do with them :-)

**Comment by amcewen** [comment] 2016-04-27 10:14
Right, @OddEssay has created a login for me so I think I can pull down whatever is needed.  I'll have a look at it at Maker Night unless anyone wants to do it before then (and lets me know what they need from the existing site)

**Comment by jamieisboss** [comment] 2016-04-27 14:46
Has anyone else heard of cloudatcost? I got one of the developer deals at 90%off which was enough to make me climb over the mountain of "this feels like a trap"  because you only pay once,  and then you can create as many vps' as you want within the resource you paid for,   so Im still dubious about it,  but  if any one can vouchsafe them it could be a good place to use as a secondary because of the non ongoing cost model or the primary but I don't know where the data centres are,  Canada maybe.  I'm just using it for playing round with things that aren't work related so a bit of latency isnt an issue but might be for you?

**Comment by DefProc** [comment] 2016-05-12 15:43
Any reason why we shouldn't just migrate straight to a wordpress specific hosting package for the short term so the website dropouts stop as quickly as possible? Especially as it has been affecting availability of the laser bookings (as they're linked from there) when it was down for a few days. 

I did see [34sp'c advert](https://www.34sp.com/wordpress-hosting) appear in my inbox.

**Comment by johnmckerrell** [comment] 2016-05-12 15:45
No, basically just someone finding the time to do it. I pulled some backups from the site last week but wasn't sure what to do with them. They probably weren't the best type of backup as they were taken from the VM, better would be an export from Wordpress itself (now the site is a little more reliable).

Important point is that DoES should "own" wherever the new site is.

**Comment by madjake45** [comment] 2016-05-12 16:01
The only issue is to look closely at the hosting offered on a package rather than a vm as a lot of companies try to limit the number of concurrent visitors and small things like that.

**Comment by DefProc** [comment] 2016-05-12 16:09
I had a quick look through the specs, and that offering does seem to be a whole vm, just set up with wordpress specific configuration. I was particularly taken by the "we'll migrate your site for you" bit though…

**Comment by jamieisboss** [comment] 2016-05-16 06:23
While i  understand the ownership of the final new site, if your existing hosting is giving you issues, We'll host the current site temporarily for you, unless there's a huge database or something weird, and it's only for a few months, i don't see that we'd need to charge you anything unless it costs us something extra. I'm sure you can always work things out with your account manager, who would be @DoESsean if there are any issues.

Separate to any name registration or hosting - I'd recommend that if you dont have one already, this would be a good time to get a [cloudflare pro account](https://www.cloudflare.com/plans/) (@$20/month for the 1st domain  [if you can live with Solve maintaining th dns, we'll do that at cost, which is $5/month as we've got clients with pro accounts already]) and move the DNS hosting to there. Reasoning being that once you're on there, there's never that potentially 48+ hour dns propagation as and when the site moves/changes/needs to failover/becomes a psychic link in the future. Also, it's much more secure, caches content, is a CDN, has a WAF, they are very good, probably better to look at their site than me telling you.

I migrate or deploy all the sites onto our live servers anyway, if you set up cloudflare then sent me  ite backup, i coud move the site onto our big(ger) VPS which will be pretty empty in a couple of days, Unless It's an unusual install, it's not a big job,  For your peace of mind, if you give me an ftp account somewhere that's still owned by DoES, Ill get it to drop full file and database backups there nightly. 

I'm not sure what access you'd want, or need, if you would even want any beyond being able to log onto wordpress but if you let me know, I'll tell you whether I'm alright with it, i say that because currently no clients on that server have direct access so I'd have to set up stuff if you wanted some. 

Offer is there, let me know.

**Comment by DefProc** [comment] 2016-05-31 08:04
After a mammoth 8 days of downtime, I got the main site content migrated over to the wordpress hosting package at 34sp last week. It seems to be stable, although it's still missing a few bits:

 - [ ] Hosted images (the wordpress importer offered to bring them — but as the old site is still down…), 
 - [ ] There is no theme (just set to the default),
 - [ ] User levels all seem to be set to the lowest level on import, 
 - [ ] The last weeknotes post was 252, *something* might need doing to get weeknotes running again (and/or any back-posts)

But at least it's up!

**Comment by amcewen** [comment] 2016-05-31 11:37
For the weeknotes the back-posts will need to be added manually.  For the future ones we just need to update the user privileges for the 'weeknotes' user and then I can set its password in the config file on my server.

And while someone (@defproc?) is updating user privileges for 'weeknotes', can they also update those for 'amcewen'.  Then I can add the missing weeknotes posts :-)

**Comment by DefProc** [comment] 2016-05-31 13:34
@amcewen both you and user weeknotes are both promoted. Just "author" level seemed fine for weeknotes, is that right?

**Comment by amcewen** [comment] 2016-05-31 23:25
Ta @DefProc.  I expect "author" is okay for the weeknotes user, but before I'd worked out what the xmlrpc endpoint is I'd got to a stage where github is rate-limiting the script, so I've not fully confirmed that :-)

I've reinstated the missing weeknotes blog posts (and posted last week's, that I'd stashed ready to post).  All was okay, apart from needing to set a custom permalink setting of "/%category%/%postname%/"

**Comment by DefProc** [comment] 2016-10-26 11:25
On the basis that the server has been up and running for *ages* without anyone having to reboot it. I'm going to close this issue. Any outstanding issues with images or theme probably fall better under issue #19, or as new issues as they are noticed.

**Closed by DefProc** 2016-10-26 11:25 UTC
Labels: 1 - You're all I need to get by, bug, Online
