### ISSUE TITLE
Most PLA requires higher temperatures than specified, I believe due to PLA pooling in nozzle.

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/somebody-should#1220] opened 2019-08-13 00:59 UTC
The issues with Prints Adam's reliability lately I think are related to the clogging of PLA in the nozzle area of the printer. Here's a timeline of what happens:

1A. Change the filament, select 210C as temperature (PLA Option).

2A. It feeds in often unsuccessfully since it gets caught or curls before entering nozzle, this then requires manual intervention.

2B. The filament feeds through fine, you then assume everything is good and then attempt to use the printer.

3A. If you were not fast enough in performing a print after manually shoving the filament in correctly, then the PLA will have solidified and pooled in the nozzle, preventing usage.

3B. The print will successfully start, but later prints may fail to begin due to pooling, and a temperature too low to liquify the pool. 

The difference between 2A and 2B is that when performing the "Change" operation, the printer pulls back the filament to prevent this pooling. This does **not** seem to happen if you abort a print, pause a print. I haven't confirmed yet, but based on the outcomes and unreliability I suspect this also doesn't happen after a print has completed.

210C is not enough to remove this pool, which then causes the printer to jam. The only solution for this is a higher temperature, OR to spend 20-30 minutes more debugging, which can often work, but does not actually solve the problem, and will eventually occur again after a few prints.

It may just be true that 210C is not enough for the filament we're using, or maybe its condition has degraded due to being exposed to moisture for months. Maybe the nozzle temperature is less than actually reported by the sensor.

I'm currently printing successfully with all PLA at what Prints Adam's sensor believes is 240C, the prints are of higher quality than I've ever had before, but are 5 degrees higher than suggested should be used as a maximum for the PLA by the vendors.

**Comment by jackie1050** [comment] 2019-08-13 06:09
Having a gap between changing the filament and starting a print didn't use to cause problems, so I think the pooling is more likely to be a symptom of another issue than the cause. 
We probably should look at storing our filament in a dry environment now we have more of a selection and it ends up being kept for longer but I can't see that making 30C difference.
Wondering if fixing the issues in #1191 and changing the nozzle might help, and if it's worth checking that the temperature sensor is working correctly.

**Comment by MatthewCroughan** [comment] 2019-08-13 06:20
@jackie1050 It does print really cleanly when going higher than specified, better than ever when using 240C. Though obviously that's a bit weird, I've made #1219 to look at better storage for the filament.

**Comment by jackie1050** [comment] 2019-08-13 06:27
That does seem odd - may be able to check by using a pale coloured filament and seeing if you get discolouration from burning.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MatthewCroughan** [comment] 2019-08-13 06:37
I'll endeavor to print small items at varying temperatures with a single filament in the week to prove this in an image.

**Comment by amcewen** [comment] 2019-08-13 09:38
I think @jackie1050 is right, this is a duplicate of #1191.  Pushing the temperature up (although we haven't had it as high as 240) is the usual workaround when the PTFE coupler has degraded.

The new couplers haven't turned up yet - although iMakr are in the US, so a couple of weeks delivery is believable.  I'll have a look at how bad Felicity's coupler is, as swapping that over might get us better printing from Prints Adam until the parts arrive

**Closed by amcewen** 2019-08-13 09:38 UTC
Labels: Tool: 3D Printer - Ultimake 2 Ext (Prints Adam), duplicate

**Comment by MatthewCroughan** [comment] 2019-08-13 09:40
@amcewen Oh wow, I didn't even know that part existed by name. Lots to learn.
