### ISSUE TITLE
Tony stopping part way through jobs when cutting.

### ISSUE THREAD

**Issue by Dinny1878** [DoESLiverpool/somebody-should#1736] opened 2022-11-09 15:31 UTC
Made some small job cuts using Tony but when attempted a slightly larger piece, Tony stopped 10% through job.

**Comment by amcewen** [comment] 2023-04-23 09:13
This looks like a duplicate of #1742 (strictly speaking that one is a duplicate of this one, but there's been more discussion over on that issue, so I'm going to close this one).

**Closed as completed by amcewen** 2023-04-23 09:13 UTC
Labels: duplicate, 2 - Should DoES, Tool: Laser Cutter - Monster (Tony)
