### ISSUE TITLE
Make a series of laser cut power test swatches for each of our sample materials

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#619] opened 2017-12-15 10:16 UTC
Here are a couple of examples:
    https://www.thingiverse.com/thing:728579
    http://www.instructables.com/id/Test-your-material-to-determine-laser-speed-and-po/

This would mean we could do away with boring tables like these:
    https://github.com/DoESLiverpool/wiki/wiki/CutEtchSettingsSophia
    https://github.com/DoESLiverpool/wiki/wiki/CutEtchSettingsGerald

It would be even better if the laser cutter could save its files with all the speeds and power settings in them so it would be easy to run one off for comparison the the reference in the middle of the day when you thought something was going wrong.  They should have dates made on them so old ones can be stored in a box to track the deterioration of the laser tube towards ordering a replacement.  

We could hang these samples on hooks along the side of the side of the machine for close inspection when selecting the feeds.

**Comment by amcewen** [comment] 2017-12-15 10:44
This is a duplicate of #414.

The laser-cutters can save their files with the speeds and power setting in (IIRC), it's just that they're the ECP files that can only be opened by the laser-cutter software and so aren't much use for anything else.

**Closed by amcewen** 2017-12-15 10:44 UTC
Labels: duplicate, Tool: Laser Cutter - Large (Gerald), Tool: Laser Cutter - Small (Sophia)
