### ISSUE TITLE
Print a list of “addresses“ we handle the postal mail for, and put it downstairs, where all the undelivered mail piles up

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#1222] opened 2019-08-14 16:35 UTC
DoES offers a mailbox service for £99/yr.

Post with "DoES Liverpool" in the address usually gets delivered to us upstairs. Everything else ends up in the pile of undelivered post under the stairs.

Sometimes post arrives for mailbox users, but because the address on the front doesn’t include "DoES Liverpool" for whatever reason, their post just gets added to the pile until someone recognises their name.

I wonder whether we could have a list, downstairs, of all our current mailbox users, so when you’re down there, you can quickly tell which items in the pile should be brought upstairs and placed in the relevant pidgeonholes?

I’m sure the landlord won’t mind us putting a list somewhere inconspicuous downstairs, especially since there’s already all manner of flyers and things down there, and _theoretically_ this list should help _reduce_ the amount of post that ends up sitting down there waiting to be noticed.

One thing I’m not sure about, though, is whether there are any data protection concerns around listing the users of our mailboxes in public. I expect most of the businesses wouldn’t mind (after all, they’re using DoES as their registered address—that’s the whole point—so the business name and its relation to DoES is probably already public knowledge) but I think we have a few _personal_ mailbox users who might not appreciate being put on a public list.

What do you think @amcewen @DoESsean? Does this annoy you as much as it annoys me?

**Comment by ajlennon** [comment] 2019-08-14 16:58
Great idea. The postie left all the mail downstairs today and I couldn’t work out which stuff to bring up (other than obvious DoES addressed mail)

**Comment by DoESsean** [comment] 2019-09-05 15:53
I can create this list very easily, but it's distribution that is the issue. We discussed in the community meeting how people may not be happy with having their company (or personal) name out in the open downstairs.

I'll be contacting them all to find out if they're comfortable with this or not, but, in the meantime, can anyone think of other ways we can make this list easily accessible? It could go in Somewhere Safe, but I don't know who would have access to that, nor how simple it would be to pull up if you were checking the mail.

**Comment by johnmckerrell** [comment] 2019-09-06 11:21
A few thoughts:

> Post with "DoES Liverpool" in the address usually gets delivered to us upstairs. 
* Yes, and this is the instruction we give, so if people are doing otherwise then I'm less concerned.
* I can create a list of the different types of members using the financial reporting tools and Freeagent. I have previously put one on Sean's desk. Of course the problem is this gets out of date quickly. I don't think it's worth (or advisable) storing this list somewhere (e.g. `somewhere-safe`).
* At least twice a week the post downstairs should be getting sorted properly by @DoESsean.
* It would help if we had somewhere downstairs to "discard" mail that has been sorted and identified as not actually belonging to anyone currently in the building, maybe a separate box which we expect the post man to pick up because it has been wrongly delivered here.

I'm mostly thinking it's not a big deal but... happy that a few simple tweaks could improve things.

**Comment by jackie1050** [comment] 2019-09-06 11:27
I'd say I often find mail addressed to permanent DoES Liverpool residents left downstairs.

________________________________

**Comment by ajlennon** [comment] 2019-09-06 13:28
fwiw imho if a business is receiving mail at DoES that should be public knowledge. It would worry me if a business wanted their contact address to be a secret

**Comment by johnmckerrell** [comment] 2019-09-09 08:30
FWIW Jason was interested in improving things downstairs and was going to start by getting some mailboxes similar to what we've got.

**Comment by DoESsean** [comment] 2022-05-26 13:03
Although we don't have a list downstairs, we do at least have one in the space now, and that seems to have made everything easier. 

Unless anyone thinks otherwise, I'm going to close this issue as we seem to have managed pretty well without this list for about two and a half years.

**Closed by DoESsean** 2022-05-26 13:03 UTC
