### ISSUE TITLE
Fusion 360 not working on CNC PC

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/somebody-should#1610] opened 2021-09-18 14:20 UTC
@RussCoty reports that Fusion 360 is not working on the CNC PC. 
He thinks the PC needs rebuilding.

**Comment by MatthewCroughan** [comment] 2021-09-18 17:55
Fusion 360's automatic update process is not flawless, it can sometimes result in a broken installation, so a reinstall of Fusion 360 should technically be all that's required.

The system is also using hard drives, which may be failing, I can debug this when I'm back in Liverpool.

My personal opinions on the CNC Room PC are that it should be running Linux, and only using Open Source software that does not auto-update and leave things in a broken state. Fusion360 and extra proprietary tools should be ran on a PC outside of the room, or on the user's laptop, as we do with LightBurn. This way, less maintenance has to occur to the system, and breakage is at least less frequent if not eliminated outright.

**Comment by Sean-anotherone** [comment] 2021-09-20 20:34
But the Kinetic CNC software runs on windows and it's proprietary.

There is something up with the PC though, as it's been grinding to a halt for some time (even after I vacuumed it out)

**Comment by MatthewCroughan** [comment] 2021-09-20 20:48
> But the Kinetic CNC software runs on windows and it's proprietary.

That is a showstopper, yes. But @goatchurchprime was talking a while ago about figuring out a way to bypass this, maybe he has some input.

I think some effort has to be made in that direction, because the Kinetic CNC software is buggy and dangerous. I can reproduce bugs where you click the "stop" button, and it instead starts a job. And activates the spindle.

**Comment by RussCoty** [comment] 2021-11-03 08:25
I have attempted a reinstall. There appeared to be 2 versions running. One older version in Chinese language as default. This would run after a lot of waiting and clicking.

The new version seems to open but is failing to connect to the internet. I suspect that the network cable needs tracing. 

Happy to look at this Thursday night if someone wants to give me a hand moving things as needed.

**Comment by MatthewCroughan** [comment] 2021-11-03 12:54
@RussCoty 

Even if you are successful, it will only require more maintenance in the future as their software upgrades break everything.

It is more sustainable to lower expectations and to use the PC for only one thing (Sending GCode). It is less sustainable to try in vain to manage self-updating proprietary software that breaks itself.

The whole model for Fusion 360 counteracts what we are trying to do, so we shouldn't push against the grain. If people want to use software that cannot be organizationally managed in any manner (without the use of complex, custom, proprietary systems), and requires manual maintenance to keep it in a working state, they should use it on their own computers. That way the maintenance burden is not ours.

The only way programs can be managed sanely is if they:
1. Do not update themselves automatically
2. Are open source

If neither of these two prerequisites are met, it is not possible to make a low maintenance system.

**Comment by arthurrowland** [comment] 2022-02-12 18:07
We could not connect the CNC PC to the internet today. And Fusion 360 will not let you use the software until the computer has an internet connection so the user can log in.

The existing WiFi dongle, and another raspberry pi branded dongle loaned from Adrian showed up in the device manager but didn't enable any wifi networking.

We replaced then tested the ethernet cable on another PC and had that working.

On the CNC PC sometimes it will show nothing under 'Network status' in settings, other times it shows no ethernet connection. The ethernet port is soldered to the motherboard, not a network card. While the case was open we re-seated the RAM which was really loose... that couldn't have been helping anything.

There seem to be other issues with the windows installation as the settings dialogs just look wrong - such as missing information / options in the security settings. So it may warrant a reinstall of the OS.

Kinetic NC still seems to work, though we didn't do any actual cutting - just jogging it around.

Did @RussCoty or @huffeec experience anything like this during the induction?

**Comment by arthurrowland** [comment] 2022-02-12 18:16
On further investigation many of the network services are stopped in the task manager, and either can't be started or stop after a second or two of being started. Looks like deep windows rot of some kind.

**Comment by MatthewCroughan** [comment] 2022-02-12 18:27
@arthurrowland I'd expect the hard drive(s) to have died by now. If you want success, you will have to reinstall the OS and Fusion 360, and also replace the drives in the machine. This maintenance will have to happen again at a later date, because of the software model we're using.

If we can get away from Fusion 360 and Windows, we won't have to maintain this as much, if at all, but that would have to rely on @goatchurchprime figuring out a way to talk to the machine without using the proprietary Kinetic NC software.

**Comment by Evans-Luke** [comment] 2022-02-17 17:27
I'm happy to do a re-install tonight if nobody objects?

**Comment by Evans-Luke** [comment] 2022-02-17 22:24
Windows has been re-installed. Fusion 360, Kinetic-NC, inkscape, GIMP and vilvaldi are installed.  Need to go through the configuration steps in the CNC-STEP folder before the router can be used.

**Comment by MatthewCroughan** [comment] 2022-02-18 01:37
@Evans-Luke Thanks for doing this.

I initially added Vivaldi when I installed the machine, because I was into it. But I'd recommend getting rid of Vivaldi in preference of Firefox/Chrome, since it's closed source and many people are not familiar with it and get confused by it, unless you installed it because you like it of course!

**Comment by Evans-Luke** [comment] 2022-02-19 22:06
Ive installed firefox onto the machine now.

Had a few issues with setting up the probe on the cnc as the machine settings imported by the ini file seemed to be reveresed (z was 110min to 0 instead of min 0 to minus 110).  This video helped  more than the manual https://www.youtube.com/watch?v=qr__04fxlWc ).  

I think the router is now setup but Its probably a good idea for somebody with more experience than me to give it a quick once over.

**Comment by Evans-Luke** [comment] 2022-02-28 16:17
Ive been using the CNC and its working well so this can now be marked as closed

**Comment by amcewen** [comment] 2022-02-28 16:28
Thanks for getting this sorted @Evans-Luke!  I've just sent you an invite to the DoES Liverpool organisation, which will let you close issues yourself in future (and get the acclaim in the #weeknotes posts :grinning:)

**Closed as completed by amcewen** 2022-02-28 16:28 UTC
Labels: 1 - Must DoES, Tool: CNC Mill - Kinetic NC

**Comment by amcewen** [comment] 2022-04-14 11:54
I've configured the hotkeys for jog and zeroing Z, documented in #1674 but noting here for next time someone is setting things up and following just this issue :grin:
