### ISSUE TITLE
Repairing Ultimaker2 extended 3D printer

### ISSUE THREAD

**Issue by akobbet** [DoESLiverpool/somebody-should#1486] opened 2020-08-29 13:13 UTC
Please make your issue: Bad printing quality.
Hi there, just wonder if anyone can help in repairing Ultimaker2 extended as the printing quality is very poor.

Thanks,

Ako

* Short (Unless required to be long)
* Specific
* Measurable
* Achievable
* Responsible
* Time-constrained

You can delete this template text.

**Comment by amcewen** [comment] 2020-09-08 13:37
Can you explain what sort of problems you're having with the print quality?  I've been printing a few thread tests on it recentlly, and there's a tiny bit of roughness on the overhangs of the thread, but the outside of the cylinder seems to be printing okay.

I've been printing at a layer height of 0.06mm, so fairly detailed prints - maybe that would help?

Do you set the temperature profiles or the type of filament in the version of Cura that you're using?  I'm **not** doing that on the one I'm using, so it's picking up the settings from the printer, but I think *some* versions of Cura do that, so maybe that's where the issue is coming in?  The printer has PETG in at the moment, I can't remember the temperature settings in it right now, but maybe check what the settings are in the printer and see if your software has anything different?

**Comment by akobbet** [comment] 2020-09-11 02:36
Hi,
Thank you for the input. I will be going to the workshop this weekend and will try to check what you have suggested as I am not able to recall what the setting I have used but I remember using the latest version of Cura (the more stable one).

Thanks,

Ako

**Comment by huffeec** [comment] 2023-01-14 21:43
Fixed by #1745

**Closed as completed by huffeec** 2023-01-14 21:43 UTC
Labels: 2 - Should DoES, Tool: 3D Printer - Ultimaker 2 Ext (Prints Adam)
