### ISSUE TITLE
Suggestion: Sample boards for laser cutters

### ISSUE THREAD

**Issue by aubergine10** [DoESLiverpool/somebody-should#499] opened 2017-05-09 18:24 UTC
Just been looking at the Cambridge makespace wiki and noticed they've created sample boards for their laser cutters, for example:

![sample](http://wiki.makespace.org/images/2/2e/Laser-schmoo-3mm-acrylic.JPG)

Would it be worth doing something similar at DoES? It looks like a great way to illustrate a) what materials can be used, and b) what effect power vs. speed settings have on those materials. Learning about materials is then just a case of "Go look at those boards over there to see what materials you can use and what settings to use on them".

I assume we'd need two sets of boards - one for Sophia, one for Gerald.

Apologies if this already exists (I noticed there are some files in `somewhere-safe` but haven't examined them to see what's in them yet).

**Comment by huffeec** [comment] 2017-05-09 21:14
This is a duplicate of #414 
Not saying it doesn't need doing, a bump isn't a bad thing, but probably best to stick to the first issue thread.

**Closed by huffeec** 2017-05-09 21:14 UTC
Labels: 3 - Could DoES, enhancement, Tool: Laser Cutter - Large (Gerald), Tool: Laser Cutter - Small (Sophia)

**Comment by aubergine10** [comment] 2017-05-09 21:35
Ah, sorry, hand't seen the earlier ticket.
