### ISSUE TITLE
Put the wiki into the same repo as the somebody-should list 

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#627] opened 2017-12-18 10:11 UTC
This has to happen because github search does all services of one repository, so when you searched it you'd see both the definitive (or out of date) documentation as well as the relevant issues.  

It's unnecessarily awkward having them separate.  It's really my fault because I first moved the wiki out to github, but didn't feel like I should intrude on the somebody-should repository, so made the https://github.com/DoESLiverpool/wiki/wiki one.  

I still don't like the somebody-should name, so maybe we could move them both off to a new more boring repo name in case people who aren't used to it are threatened by it.  We ought to focus group the name with noobs (or have a short session about it at a public meeting), because us old-timers have become too accustomed to it.

**Comment by amcewen** [comment] 2018-11-17 14:45
#801 is a duplicate of this, but given that that one has more activity, I'm going to close this one.

**Closed by amcewen** 2018-11-17 14:45 UTC
Labels: System: Issue Tracker, System: Website, System: Wiki, duplicate
