### ISSUE TITLE
Add stuff to the Maker-night wiki page

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/somebody-should#286] opened 2016-05-16 20:05 UTC
This one: https://github.com/DoESLiverpool/wiki/wiki/Maker-night

Needs a few names and hints about who comes (eg JR), how to find the place, links to weeknotes of some stuff done.

**Comment by amcewen** [comment] 2016-06-01 10:46
Given that @helicalbytes and @huffeec have been working on a refresh of makernight.co.uk this is either a duplicate of #74 or #74 is a duplicate of this... :-)

**Comment by huffeec** [comment] 2017-02-01 23:12
I've add a new page for makers linked from the Maker-night page to show the people who come to maker events. 
https://github.com/DoESLiverpool/wiki/wiki/Makers

This could become content for #74

**Comment by jackie1050** [comment] 2017-02-02 00:54
I’ll fix this tomorrow . . .

**Comment by huffeec** [comment] 2017-02-02 20:34
I've set up an Instagram account for DoES Liverpool to capture the range of things made. Again this either could be a stand alone account or to generate content for #74 
https://www.instagram.com/doesliverpool/

It's against the makernight@doesliverpool.com account, I'll send the password to everyone on that account. Not sure a better way to disseminate the password, but if you want to add images it's probably best to email the maker account and we can send it on?

The wiki still needs adding to but I think we're far enough on to call this closed?

**Closed by huffeec** 2017-02-02 20:34 UTC
Labels: 2 - The time is now, Online
