### ISSUE TITLE
Broadband doesn't seem to be working as well as it was

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/somebody-should#1664] opened 2022-02-22 15:36 UTC
I've had on and off problems with the broadband for the past few weeks and the BeeCam project is no longer working very well as the A/V keeps buffering. I replaced the live feeds with a test stream to YouTube and I still see the problem.

I am trying to dig out some packet loss, latency and jitter measurement tools and my initial non-scientific results are that we seem to be getting a fair bit of bursty packet loss.

IANANA (I am not a network administrator) so can anybody advise? @johnmckerrell ?

![image](https://user-images.githubusercontent.com/1537834/155165887-2106e87d-d173-49f7-9a9e-1131abc5dcec.png)

**Comment by ajlennon** [comment] 2022-02-22 15:49
OK I have cut the Bee stuff completely out of the loop and am running this `FFMPEG` test to YouTube on my laptop. This works for a bit then data is no longer received at the YouTube end although it's still sending from my laptop. Pretty sure this all used to work fine

```
ffmpeg -f lavfi -i testsrc=size=1280x720:rate=25 -f lavfi -i sine=f=440:b=4 -shortest -codec:v libx264 -b:v 2048k -c:a aac -b:a 128k -f flv rtmp://a.rtmp.youtube.com/live2/$STREAM_KEY
```

**Comment by MatthewCroughan** [comment] 2022-02-22 18:27
It is my understanding that Baltic Broadband have switched over to radio/wireless infrastructure fully. I think that we are no longer receiving a gigabit fiber link to the point of presence downstairs and should expect a higher contention ratio with other customers, as well as more packet loss when their radio equipment gets jostled in storms.

Is it true that everything is radio based now? @johnmckerrell

**Comment by MatthewCroughan** [comment] 2022-02-22 18:30
From https://github.com/DoESLiverpool/somebody-should/issues/1653:
> I believe they’ve made an improvement if someone in the space could try it. From the sounds of things we are no longer on a hard fibre but are served by “radio” so that might be part of the reason we’re seeing a change. I’ll ask more about that when I confirm whether we’re seeing an improvement or not.

**Comment by ajlennon** [comment] 2022-02-22 19:24
Yes that's my understanding too. That doesn't help me address the issues I am seeing though.

**Comment by MatthewCroughan** [comment] 2022-02-22 19:46
@ajlennon You and I could both foot the bill to get gigabit fiber back in, I'm willing to go half on that. The price of adding gigabit would be £100/month extra on top of what we have, so both of us could pay £50/month towards it.

DoES currently pays £150/month for the current plan, so in total the contract would be £250/month from DoES' perspective.

**Comment by ajlennon** [comment] 2022-02-22 20:08
What is DoES paying for?

**Comment by johnmckerrell** [comment] 2022-02-22 21:35
We have the £150 Aurora package on this page: https://www.balticbroadband.com/broadband-wireless/

**Comment by johnmckerrell** [comment] 2022-02-22 21:39
I can get in touch with them again to report continuing problems but having as much information as possible would be useful. What timespan is covered by the first image on this issue?

**Comment by ajlennon** [comment] 2022-02-22 21:41
Thanks John - I'll try to do some more testing tomorrow and be a bit more specific?

**Comment by amcewen** [comment] 2022-02-23 10:56
We've had no Internet since 9:46 this morning.  It seems to just be us (Aeternum are fine, and also on Baltic).

Baltic noticed before we told them, and phoned up to check.  They didn't seem to be able to see their router, but I've confirmed with them that it's on and has some flashing lights, so seems like it's up at this end.  They're looking into it further and going to give us a call back when they've got more info.

**Comment by MatthewCroughan** [comment] 2022-02-23 13:03
I noticed @amcewen's response 10 minutes ago, and have been periodically pinging my box. As of just now, the network is accessible, then went offline again. So it seems as if the network connectivity is intermittent, rather than completely offline.

**Comment by amcewen** [comment] 2022-02-23 14:40
Baltic have been out and replaced their router, and once we'd restarted the Ethernet switch at the edge of our network things seem back up and running okay.

Not quite sure why a dumb Ethernet switch should need a reboot to fix things, but that's what did the trick.

**Comment by ajlennon** [comment] 2022-02-23 14:41
How strange !

**Comment by MatthewCroughan** [comment] 2022-02-23 15:00
@amcewen Dumb ethernet switches still store state like the ARP cache, who knows whether the switch disabled some ports due to spanning tree? Or learned the wrong info when MAC learning during the switchover. State causes all sorts of problems. My PFSense router also required a reboot in the last downtime when Baltic had a routing error, for who knows what reason.

For reasons like this, I'm going to use https://scion-architecture.net/ at a datacenter in Wales where I'm going to start hosting boxes, I believe it will get around these sorts of networking problems. Would be good to try and get a SCION node installed at Edge5 and maybe the POP below DoES, then we could also see sub-millisecond latency. Worth looking into if you dig networking.

**Comment by ajlennon** [comment] 2022-02-23 15:58
These are the latest (building and tested) dunfell builds

https://github.com/DynamicDevices/meta-mono/actions/runs/1794025332

**Comment by ajlennon** [comment] 2022-02-25 14:48
Haven't had a chance to do more testing at DoES I'm afraid @johnmckerrell  but I will when I'm in next. 

For a comparison I ran the same thing here (home, Virgin Media via WiFI) and nothing seems to get dropped

@see https://packetlosstest.com/

![image](https://user-images.githubusercontent.com/1537834/155735392-37d1afc6-a942-4760-be9f-ea1608940ddf.png)

**Comment by ajlennon** [comment] 2022-02-26 14:48
I've been footling around. I found this thing Prometheus that monitors all sorts of things, and there's a node_exporter application that generates a load of metrics. So I have that running on my Pi in the BeeHive now and I am graphing up the metrics with Grafana. It's all quite nice actually.

So will leave this running and see if anything leaps out

![image](https://user-images.githubusercontent.com/1537834/155847393-d046c9a0-0b34-4563-b61b-b8f7ad2953f2.png)

[https://grafana.dynamicdevices.co.uk:3000/d/rYdddlPWk/node-exporter-full?orgId=1&refresh=1m](https://grafana.dynamicdevices.co.uk:3000/d/rYdddlPWk/node-exporter-full?orgId=1&refresh=1m)

**Comment by ajlennon** [comment] 2022-02-28 13:38
So I just did a test now 28/02/22 13:38 and it is looking good... Need to work out how it changes over time

![image](https://user-images.githubusercontent.com/1537834/155992635-7257cbff-4ba8-4e2c-8829-473d6f00453f.png)

**Comment by cameronswift** [comment] 2022-03-07 12:44
> I've been footling around. I found this thing Prometheus that monitors all sorts of things, and there's a node_exporter application that generates a load of metrics. So I have that running on my Pi in the BeeHive now and I am graphing up the metrics with Grafana. It's all quite nice actually.
> 
> So will leave this running and see if anything leaps out
> 
> ![image](https://user-images.githubusercontent.com/1537834/155847393-d046c9a0-0b34-4563-b61b-b8f7ad2953f2.png)
> 
> https://grafana.dynamicdevices.co.uk:3000/d/rYdddlPWk/node-exporter-full?orgId=1&refresh=1m
![graph](https://user-images.githubusercontent.com/94469375/157033815-8d55949a-9cf1-414f-9a5e-c9afe02df4fd.jpg)

After being left for a few days to run, we can now see this graph showing a problem with the connection.

**Comment by MatthewCroughan** [comment] 2022-03-07 13:43
I've just set up Smokeping monitoring Cloudflare and Google, there's already some evidence of packet loss. So we'll see how it goes.

![image](https://user-images.githubusercontent.com/26458780/157045450-f33e614b-200c-4917-a448-a1774a9fdfad.png)

**Comment by MatthewCroughan** [comment] 2022-03-18 20:20
The following is some data from Smokeping over a 10 day period. The anomaly on the 13th March is because I have a WWAN/4G connection on the machine which was preferred due to a routing error with Baltic, I believe. Shortly after their routing error was sorted out, my machine resumed using Baltic.

# Pinging Google
![image](https://user-images.githubusercontent.com/26458780/159077637-2b04a8e5-b695-4fef-8751-d2660d001be8.png)

# Pinging Cloudflare
![image](https://user-images.githubusercontent.com/26458780/159077664-24d728e2-572b-4576-a399-50c25f2e8473.png)

**Comment by ajlennon** [comment] 2022-04-27 16:05
Quick update on this. I've been chatting to Matt Wilson @ Baltic Broadband who has been really helpful and put me onto Syd to talk about the issues we've been seeing.

Syd has explained to me the thinking is this is due to the way the bracket is constructed that holds the radio antenna which provides connectivity for DoES. In particular we've had all these bad storms which have affected the positioning and the chaps have had to come out to fix it.

So I'm told the plan is to regineer the bracket so it doesn't move about and this should address the issues we are seeing.

Great news and I will keep you posted when I know more...

**Comment by zarino** [comment] 2024-10-27 15:43
There have been no updates on this issue for two years, and I’ve not heard any complaints about the internet recently, so I’m going to close this issue.

Feel free to re-open if you think there’s still something _somebody should_ do here!

**Closed as completed by zarino** 2024-10-27 15:43 UTC

**Comment by ajlennon** [comment] 2024-10-27 18:30
Ah that was me wasn't it. Not sure of the ins and outs but the TL;DR is that weather had knocked an antenna out of place and Matt's team got it all sorted out I think 🙏
