### ISSUE TITLE
Fill in CIC34 form for 2019-2020 year

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1413] opened 2020-03-23 13:26 UTC
We really need to do this in July or August so that it's nice and fresh in our minds!

As a CIC we must fill in the CIC34 form. We don't tend to provide a lot of information on here given we communicate with the community through other mechanisms but can give a brief update on our activities during the year.

The contents of the previous form are in issue #1053. The following headings must be completed:

* PART 1 - GENERAL DESCRIPTION OF THE COMPANY’S ACTIVITIES AND IMPACT
  In the space provided below, please insert a general account of the company’s activities in the financial year to which the report relates, including a description of how they have benefited the community.
* PART 2 – CONSULTATION WITH STAKEHOLDERS – Please indicate who the company’s stakeholders are; how the stakeholders have been consulted and what action, if any, has the company taken in response to feedback from its consultations? If there has been no consultation, this should be made clear.
* PART 3 – DIRECTORS’ REMUNERATION – if you have provided full details in your accounts you need not reproduce it here.  Please clearly identify the information within the accounts and confirm that, “There were no other transactions or arrangements in connection with the remuneration of directors, or compensation for director’s loss of office, which require to be disclosed” (See example with full notes). If no remuneration was received you must state that “no remuneration was received” below.
* PART 4 - TRANSFER OF ASSETS OTHER THAN FOR FULL CONSIDERATION- Please insert full details of any transfers of assets other than for full consideration e.g. Donations to outside bodies.  If this does not apply you must state that “no transfer of assets other than for full consideration has been made” below.

**MAKE SURE TO FILL IN ALL PARTS!**

**Comment by amcewen** [comment] 2021-12-21 20:14
Duplicate of #1464

**Closed by amcewen** 2021-12-21 20:14 UTC
Labels: duplicate, help wanted, 2 - Should DoES, Holding out for a hero, Community, Finance
