### ISSUE TITLE
Fix fault in Octoscreen causing issues with our Octoprint enabled printers

### ISSUE THREAD

**Issue by jackie1050** [DoESLiverpool/somebody-should#1325] opened 2019-11-25 07:20 UTC
An error in the Octoprint? software means that the printer screens are displaying an error message (the error is due to opening threads and not closing them).
Apparently the CR-10S can be used if turned off and on again and the others need to be stopped and started in the app.(@mattcroughan is going to make some temporary labels explaining what to do in the short term).

**Comment by MatthewCroughan** [comment] 2019-11-25 19:02
This issue is referenced here, already being worked on. It's not a fault with octoprint, but with Octoscreen.

https://github.com/Z-Bolt/OctoScreen/issues/56

**Comment by MatthewCroughan** [comment] 2019-11-25 19:12
Octoscreen tells Octoprint to automatically connect to the printer every 5 seconds or so. This causes a memory leak to occur as the threads that do this are not being closed. This then means the connections are still open to Octoprint's api, thus running Octoprint out of memory eventually, since it cannot handle connections from that many clients. Octoscreen is written in golang, which I don't understand fully yet, though am working on thanks to this issue. Maybe @paulfurley could take a quick look at this? I believe the problem is in the threading logic in common.go:

https://github.com/Z-Bolt/OctoScreen/blob/fc33e3a0f986cef3105fbada95870bcdb9b54b61/ui/common.go#L163

Or from the function `verifyConnection()` in ui.go:

https://github.com/Z-Bolt/OctoScreen/blob/fc33e3a0f986cef3105fbada95870bcdb9b54b61/ui/ui.go#L121

Importantly, `verifyConnection()` is called by ui.update.

https://github.com/Z-Bolt/OctoScreen/blob/fc33e3a0f986cef3105fbada95870bcdb9b54b61/ui/ui.go#L80

This spawns a new background process every two seconds for this, which is always ran regardless of if one is still in the background. I just don't know enough about golang to have this not occur.

https://github.com/Z-Bolt/OctoScreen/issues/56

**Comment by ajlennon** [comment] 2019-11-25 19:53
So you think this is a problem in the underlying Golang framework? We have a chap coming up at the weekend who might also be able to advise if so

**Comment by MatthewCroughan** [comment] 2019-11-25 19:58
@ajlennon The problem could be fixed in Octoprint by having it close connections on clients that have been connected for too long a period of time, or by catching the MemoryError exception in Tornado and at the very least crashing, if not clearing up old client connections. https://github.com/foosel/OctoPrint/issues/3343

In Go, as far as I can tell, common.go is written by the author of a particular thing to act as a toolset. So the threading logic is either copy and pasted from somewhere, or improperly written by the author if this is a problem. Although, maybe the thinking is that `verifyConnection()` is supposed to close the thread after it's ran? Or at the very least check if a thread is open and close if if so. I just don't know enough to know where the problem is in that regard. I wouldn't call it a problem with the framework without knowing for sure.

Would like to see someone with more knowledge fix the issue so I can learn from them, so whoever is coming in, let me know when they are so I can be around!

**Comment by ajlennon** [comment] 2019-11-25 19:58
Connections should time out.

**Comment by MatthewCroughan** [comment] 2019-11-25 20:03
@ajlennon I haven't observed connections timing out. Octoprint's log doesn't suggest there is any timing out occuring, although it does tell me that when haproxy fails to serve a client, for example. The REST api that Octoprint implements may not for some reason time clients out. I don't know enough about how APIs are implemented to know if that's the case, but all I observe is that threads are allowed to endlessly accumulate in Octoscreen, along with the number of outgoing TCP connections until Octoprint's usage of Tornado crashes with MemoryError, which has been noted in the Octoprint issue.

**Comment by MatthewCroughan** [comment] 2019-11-25 20:09
There is also this issue from 2018 which goes into some more detail about the same sort of thing I discovered.

https://github.com/mcuadros/OctoPrint-TFT/issues/15

**Comment by MatthewCroughan** [comment] 2019-12-08 17:46
I've narrowed this down to being more likely to be an issue in Octoprint. 
https://github.com/foosel/OctoPrint/issues/3376

**Comment by MatthewCroughan** [comment] 2019-12-11 03:28
I've effectively worked around this issue for the time being in this commit:
 https://github.com/MatthewCroughan/octobalena/commit/719f29c2f99707c2dabcb025b522057d040eb35a 
This doesn't fix the root cause which is a memory leak in the Tornado web framework used by Octoprint. But it absolutely resolves our usability issue with the printers for the time being.

I will begin documenting how to use these printers once I get back from Wales.

**Closed by MatthewCroughan** 2019-12-11 03:28 UTC
Labels: Tool: 3D Printer - Other

**Comment by ajlennon** [comment] 2019-12-11 09:26
Don't they have internet in Wales? ;)
