### ISSUE TITLE
Gerald bed is sloping toward the window

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/somebody-should#343] opened 2016-09-08 16:54 UTC
Noticed earlier that the bed is sloping down toward the window so bed will have to be looked at as its making cuts and etches fade out in the window side half of the bed. Didnt have time to look into it properly: it seems to be the bed frame thats sloping so usual quick fix of propping up the right side with spacers may not cut it. Didnt have time to investigate further.

**Comment by amcewen** [comment] 2016-10-07 16:06
This is a duplicate of #288 - which hasn't been fixed yet either :-/ but is (a) older and (b) has more information in it (so I'm going to close this one)

**Closed by amcewen** 2016-10-07 16:06 UTC
Labels: 1 - You're all I need to get by, bug, duplicate, Gerald the Gigantic Laser Cutter, help wanted, maintenance, Workshop
