### ISSUE TITLE
Investigate "Electrically Powered Hold Open Device" for the main entrance door

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/somebody-should#921] opened 2018-09-20 10:33 UTC
The DHF+GAI Code of Practice<small>[1]</small> describes "Electrically Powered Hold Open Devices" that, when connected to the building fire detection system or their own local detectors, provide a safe solution for keeping fire doors open during normal use, but having them close automatically when a fire is detected nearby.

The government’s own guidance<small>[2]</small> states:

> Such devices are particularly useful in situations where self-closing doors on escape routes are used regularly by significant numbers of people, or by people with impaired mobility who may have difficulty in opening the doors.

Just like our main door!

[1] http://firecode.org.uk/Code%20of%20Practice%202009%20Issue%203.pdf
[2] https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/422175/9449_Offices_and_Shops_v2.pdf

/cc @goatchurchprime

**Comment by johnmckerrell** [comment] 2018-09-20 10:39
We did mention this at the recent directors meeting, minutes of which are….. on their way ;-) We’ll ask Tam what he knows about it, I wouldn’t think it would be all that expensive. I do still prefer not to have that door left open as a matter of course though as it does allow anyone that has accessed the building to get into our space whether we want them to or not. If the landing is not welcoming enough for the 30seconds that you pass through it then maybe we should look at fixing that instead?

**Comment by amcewen** [comment] 2018-09-20 12:00
Personally, I prefer being able to have the door to the main space open (and closed if there's no-one left in the main room) but don't mind too much.

I do think we should have a proper way to leave the events room door open when there's an event on, however.

**Comment by amcewen** [comment] 2018-12-02 22:51
#923 is a duplicate of this, but seems to have more detail about what we bought, so I'm going to close this one.

**Closed by amcewen** 2018-12-02 22:51 UTC
Labels: 2 - Should DoES, Health & Safety, Room: Main Room, duplicate
