### ISSUE TITLE
doorbot1 isn't running logcards

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#349] opened 2016-09-29 12:23 UTC
Just tried to update the logcards config, and doorbot one doesn't seem to be running the logcards script, and there's no `screen` session running. 

As it stands, the main room is only accessible by an actual key.

**Comment by amcewen** [comment] 2016-09-29 18:54
It seems it still had the old broken config.yaml which contained an accented character, and if logcards isn't running you tend to tell the update-rfid script that things haven't gone well, at which point it reverts from the new, would've worked config to the old still doesn't work config :-)  I've updated the config on all three doorbots (Doorbot3 needed a reboot to be on the network).

So effectively a duplicate of #347.

**Comment by DefProc** [comment] 2016-10-13 12:28
Today we just rebooted the doorbot, and logcards didn't come up cleanly again (no screen session running). To fix, I ran:

 *  `sudo screen` 
 *  `./run_logcards.sh` 
 * then `Ctrl+A`, `d` to detach and leave it running

And everything started fine.

I've not checked why it didn't come up cleanly, so it's possible it'll happen again.

**Comment by DefProc** [comment] 2016-11-10 12:59
This has happened again with a reboot today, so we'll need to take another look at why it's not running logcards automatically on startup.

**Comment by amcewen** [comment] 2017-02-16 23:07
Fixed with the complete reinstall done in #426.

**Closed by amcewen** 2017-02-16 23:07 UTC
Labels: 1 - You're all I need to get by, Broken, Main Room
