### ISSUE TITLE
Get a banner/pull up board for exhibits

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/somebody-should#427] opened 2017-01-19 10:50 UTC
We're often fairly light on large scale DoES Liverpool specific branding. 

Something like a pull up banner would go well at one end or behind a stand.

**Comment by amcewen** [comment] 2017-01-19 11:08
I think we need to make some progress on it rather than raise a new issue about it each January... :-D

This is a duplicate of #254...

**Closed by amcewen** 2017-01-19 11:08 UTC
Labels: 2 - The time is now

**Comment by DefProc** [comment] 2017-01-19 14:21
Ah, I only did a text search for banner!
